### ISSUE TITLE
Error when run pytest

### ISSUE THREAD

**Issue by JTQIN** [landlab/landlab#1089]
Hi,

I installed the landlab successfully under the "Developer" mode on a Windows 10 platform Anaconda. However, when I tried to run the pytest, 1 error occured as the following. Could you please give me some suggestion on how to deal with it? Thanks.

Best,

Jintang

 ____________________________________________ ERROR collecting test session ____________________________________________
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\_pytest\config\__init__.py", line 458, in _importconftest
    return self._conftestpath2mod[key]
KeyError: WindowsPath('D:/landlab-master/landlab/tests/conftest.py')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\_pytest\config\__init__.py", line 464, in _importconftest
    mod = conftestpath.pyimport()
  File "C:\ProgramData\Anaconda3\lib\site-packages\py\_path\local.py", line 701, in pyimport
    __import__(modname)
  File "D:\landlab-master\landlab\__init__.py", line 29, in <module>
    from .grid import (
  File "D:\landlab-master\landlab\grid\__init__.py", line 13, in <module>
    from .create import create_and_initialize_grid, create_grid
  File "D:\landlab-master\landlab\grid\create.py", line 8, in <module>
    from ..io import read_esri_ascii
  File "D:\landlab-master\landlab\io\__init__.py", line 17, in <module>
    from .shapefile import read_shapefile
  File "D:\landlab-master\landlab\io\shapefile\__init__.py", line 1, in <module>
    from .read_shapefile import read_shapefile
  File "D:\landlab-master\landlab\io\shapefile\read_shapefile.py", line 6, in <module>
    import shapefile as ps
ModuleNotFoundError: No module named 'shapefile'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\py\_path\common.py", line 377, in visit
    for x in Visitor(fil, rec, ignore, bf, sort).gen(self):
  File "C:\ProgramData\Anaconda3\lib\site-packages\py\_path\common.py", line 418, in gen
    dirs = self.optsort([p for p in entries
  File "C:\ProgramData\Anaconda3\lib\site-packages\py\_path\common.py", line 419, in <listcomp>
    if p.check(dir=1) and (rec is None or rec(p))])
  File "C:\ProgramData\Anaconda3\lib\site-packages\_pytest\main.py", line 622, in _recurse
    ihook = self.gethookproxy(dirpath)
  File "C:\ProgramData\Anaconda3\lib\site-packages\_pytest\main.py", line 441, in gethookproxy
    my_conftestmodules = pm._getconftestmodules(fspath)
  File "C:\ProgramData\Anaconda3\lib\site-packages\_pytest\config\__init__.py", line 436, in _getconftestmodules
    mod = self._importconftest(conftestpath)
  File "C:\ProgramData\Anaconda3\lib\site-packages\_pytest\config\__init__.py", line 472, in _importconftest
    raise ConftestImportFailure(conftestpath, sys.exc_info())
_pytest.config.ConftestImportFailure: (local('D:\\landlab-master\\landlab\\tests\\conftest.py'), (<class 'ModuleNotFoundError'>, ModuleNotFoundError("No module named 'shapefile'"), <traceback object at 0x000001A5007F7F88>))
================================================== warnings summary ===================================================
landlab\utils\decorators.py:149
landlab\utils\decorators.py:149
landlab\utils\decorators.py:149
landlab\utils\decorators.py:149
landlab\utils\decorators.py:149
landlab\utils\decorators.py:149
landlab\utils\decorators.py:149
landlab\utils\decorators.py:149
landlab\utils\decorators.py:149
landlab\utils\decorators.py:149
landlab\utils\decorators.py:149
landlab\utils\decorators.py:149
landlab\utils\decorators.py:149
landlab\utils\decorators.py:149
landlab\utils\decorators.py:149
landlab\utils\decorators.py:149
landlab\utils\decorators.py:149
landlab\utils\decorators.py:149
landlab\utils\decorators.py:149
landlab\utils\decorators.py:149
  D:\landlab-master\landlab\utils\decorators.py:149: DeprecationWarning: `formatargspec` is deprecated since Python 3.5. Use `signature` and the `Signature` object directly
    argspec=inspect.formatargspec(*argspec),

-- Docs: https://docs.pytest.org/en/latest/warnings.html
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: 1 error during collection !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
============================================ 20 warnings, 1 error in 1.99s ============================================

**Comment by nathanlyons** [comment]
Hi @JTQIN. Did you run the following line:
```
python setup.py develop
```
as described here: https://landlab.readthedocs.io/en/release/development/install/install.html

I ask because I see that the error is `ModuleNotFoundError: No module named 'shapefile'`. 'shapefile` is a module of pyshp, which should be installed with the line above.

Another possibility: did you run the line above in a Conda environment, for example 'landlab-dev'? If yes, pytest and landlab should be run in that environment.

**Comment by JTQIN** [comment]
Hi Nathan,

Thanks a lot. The problem is solved following your suggestion. You are right. I did not run "pytest" under "landlab-dev".

Jintang

**Comment by kbarnhart** [comment]
@JTQIN if you have any recommendations for how we might revise our developer installation instructions so that they are clearer, please let us know by commenting on this issue.

**Comment by JTQIN** [comment]
@kbarnhart Thanks, Kati. I will do so:)

**Comment by kbarnhart** [comment]
@JTQIN it looks like we've addressed your issue so I'm closing this. If you have any other questions, please comment or open another issue.
