### ISSUE TITLE
Create builds for Python 3.8?

### ISSUE THREAD

**Issue by kbarnhart** [landlab/landlab#1109]
@mcflugen I was just testing some of our install instructions... I blindly made an empty conda environment and installed landlab with 

```
pip install --pre landlab
```

this totally failed with `ModuleNotFoundError: No module named 'numpy'`

It took me a moment to figure out that this was because the environment I had created was python 3.8. 

Perhaps we should start building for 3.8. Do you know of any barriers to doing that?

Error log below:

```
Last login: Wed Jan 15 09:42:27 on ttys000
(base) barnhark@rgnt-2-71-169-edu ~ % conda create --name test
Collecting package metadata (current_repodata.json): done
Solving environment: done


==> WARNING: A newer version of conda exists. <==
  current version: 4.8.0
  latest version: 4.8.1

Please update conda by running

    $ conda update -n base -c defaults conda



## Package Plan ##

  environment location: /Users/barnhark/opt/anaconda3/envs/test



Proceed ([y]/n)? y

Preparing transaction: done
Verifying transaction: done
Executing transaction: done
#
# To activate this environment, use
#
#     $ conda activate test
#
# To deactivate an active environment, use
#
#     $ conda deactivate

(base) barnhark@rgnt-2-71-169-edu ~ % conda activate test
(test) barnhark@rgnt-2-71-169-edu ~ % conda install pip
Collecting package metadata (current_repodata.json): done
Solving environment: done


==> WARNING: A newer version of conda exists. <==
  current version: 4.8.0
  latest version: 4.8.1

Please update conda by running

    $ conda update -n base -c defaults conda



## Package Plan ##

  environment location: /Users/barnhark/opt/anaconda3/envs/test

  added / updated specs:
    - pip


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    setuptools-45.0.0          |           py38_1         646 KB  conda-forge
    ------------------------------------------------------------
                                           Total:         646 KB

The following NEW packages will be INSTALLED:

  ca-certificates    conda-forge/osx-64::ca-certificates-2019.11.28-hecc5488_0
  certifi            conda-forge/osx-64::certifi-2019.11.28-py38_0
  libcxx             conda-forge/osx-64::libcxx-9.0.1-1
  libffi             conda-forge/osx-64::libffi-3.2.1-h6de7cb9_1006
  ncurses            conda-forge/osx-64::ncurses-6.1-h0a44026_1002
  openssl            conda-forge/osx-64::openssl-1.1.1d-h0b31af3_0
  pip                conda-forge/osx-64::pip-19.3.1-py38_0
  python             conda-forge/osx-64::python-3.8.1-h5c2c468_1
  readline           conda-forge/osx-64::readline-8.0-hcfe32e1_0
  setuptools         conda-forge/osx-64::setuptools-45.0.0-py38_1
  sqlite             conda-forge/osx-64::sqlite-3.30.1-h93121df_0
  tk                 conda-forge/osx-64::tk-8.6.10-hbbe82c9_0
  wheel              conda-forge/osx-64::wheel-0.33.6-py38_0
  xz                 conda-forge/osx-64::xz-5.2.4-h1de35cc_1001
  zlib               conda-forge/osx-64::zlib-1.2.11-h0b31af3_1006


Proceed ([y]/n)? y


Downloading and Extracting Packages
setuptools-45.0.0    | 646 KB    | ##################################### | 100%
Preparing transaction: done
Verifying transaction: done
Executing transaction: done
(test) barnhark@rgnt-2-71-169-edu ~ % pip install landlab --pre
Collecting landlab
  Downloading https://files.pythonhosted.org/packages/41/eb/e2d91be6a91d341152859061e2c11ca7555bce83018eeec43386bd3b3824/landlab-1.9.0.tar.gz (823kB)
     |████████████████████████████████| 829kB 886kB/s
    ERROR: Command errored out with exit status 1:
     command: /Users/barnhark/opt/anaconda3/envs/test/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/2n/p_sdc7vx1xzcnnmhvpl3zs0c0000gn/T/pip-install-8uoiywj0/landlab/setup.py'"'"'; __file__='"'"'/private/var/folders/2n/p_sdc7vx1xzcnnmhvpl3zs0c0000gn/T/pip-install-8uoiywj0/landlab/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/2n/p_sdc7vx1xzcnnmhvpl3zs0c0000gn/T/pip-install-8uoiywj0/landlab/pip-egg-info
         cwd: /private/var/folders/2n/p_sdc7vx1xzcnnmhvpl3zs0c0000gn/T/pip-install-8uoiywj0/landlab/
    Complete output (16 lines):
    Traceback (most recent call last):
      File "/Users/barnhark/opt/anaconda3/envs/test/lib/python3.8/site-packages/pkg_resources/__init__.py", line 360, in get_provider
        module = sys.modules[moduleOrReq]
    KeyError: 'numpy'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/2n/p_sdc7vx1xzcnnmhvpl3zs0c0000gn/T/pip-install-8uoiywj0/landlab/setup.py", line 14, in <module>
        numpy_incl = pkg_resources.resource_filename("numpy", "core/include")
      File "/Users/barnhark/opt/anaconda3/envs/test/lib/python3.8/site-packages/pkg_resources/__init__.py", line 1145, in resource_filename
        return get_provider(package_or_requirement).get_resource_filename(
      File "/Users/barnhark/opt/anaconda3/envs/test/lib/python3.8/site-packages/pkg_resources/__init__.py", line 362, in get_provider
        __import__(moduleOrReq)
    ModuleNotFoundError: No module named 'numpy'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
(test) barnhark@rgnt-2-71-169-edu ~ %
```

**Comment by mcflugen** [comment]
@kbarnhart I've started #1111 to try to fix this issue.
