### ISSUE TITLE
Import issue with depression_finder.cfuncs

### ISSUE THREAD

**Issue by pfeiffea** [landlab/landlab#1165]
I'm working from the developer branch of landlab. When I try to import `FlowDirectorSteepest` I get an error saying that `depression_finder.cfuncs` is not found

```
 from landlab.components import FlowDirectorSteepest
Traceback (most recent call last):

  File "<ipython-input-3-d6c61a29118e>", line 1, in <module>
    from landlab.components import FlowDirectorSteepest

  File "c:\users\pfeif\documents\github\landlab\landlab\components\__init__.py", line 2, in <module>
    from .depression_finder import DepressionFinderAndRouter

  File "c:\users\pfeif\documents\github\landlab\landlab\components\depression_finder\__init__.py", line 1, in <module>
    from .lake_mapper import DepressionFinderAndRouter

  File "c:\users\pfeif\documents\github\landlab\landlab\components\depression_finder\lake_mapper.py", line 16, in <module>
    from .cfuncs import find_lowest_node_on_lake_perimeter_c

ModuleNotFoundError: No module named 'landlab.components.depression_finder.cfuncs' 
```

When I navigate to landlab--> landlab-->components-->depression_finder I see a file called cfuncs.pyx

Any suggestions?

**Comment by SiccarPoint** [comment]
Did you try re-entering `python setup.py develop` from a terminal? cfuncs issues are often easily resolved this way.

**Comment by pfeiffea** [comment]
That did the trick, thank you!
