### ISSUE TITLE
Using the Landlab notebooks

### ISSUE THREAD

**Issue by gregtucker** [landlab/landlab#1272]
I'm trying to get started with Landlab and have gotten to the landlab_notebooks environment using Anaconda but I cannot access any notebooks using Jupyter. If you could direct me to a help page or assist with this matter I would greatly appreciate it.

**Comment by gregtucker** [comment]
Here's my guess about what's going on:
* You probably followed the instructions for a regular (non-developer) installation of Landlab
* When you run `jupyter notebook notebooks/welcome.ipynb`, you get a message saying that there is no such file or directory
* The reason is probably that the regular installation places all the files in a special folder location that is not easy to find: the notebooks are on your computer, but they are located with all of Landlab's Python source files in a location like `/opt/anaconda3/lib/python3.7/site-packages/landlab` (depending on your platform, Python version, etc.)

Short-term solution:
* Option 1: if you are comfortable navigating in a command window, find the directory containing the Landlab source and navigate to it, and then into the sub-folder that contains the notebooks. On a mac, it is probably something like `/opt/anaconda3/lib/python3.7/site-packages/landlab/notebooks`. Copy the notebooks folder and its contents to a location in your own user space. Run `jupyter notebook`, navigate to your copy of the notebooks folder, and open `welcome.ipynb`.
* Option 2: download a copy of the Landlab sources, including the notebooks. To do this, navigate a web browser to `https://github.com/landlab/landlab`. Click the green "Code" button, then select "Download ZIP". Save the `landlab-master.zip` file in a convenient location on your computer, and double-click to open it (it's a big file and might take a few minutes to download). Once downloaded and unzipped, you will find all of the notebooks in the sub-folder `landlab-master/notebooks`.
* Option 3: run the notebooks in the cloud using Binder. The link for this is listed on the [Tutorials  page](https://landlab.readthedocs.io/en/latest/user_guide/tutorials.html) under "Launch notebooks online".

Longer-term solution:

We need a way that a user who follows the instructions under "Launch notebooks locally" actually ends up with the notebooks in an easily findable/accessible location on their computer. I'm leaving this Issue open as a place to discuss possible methods. One approach would be to maintain a separate GitHub repo that always contains a copy of the notebooks associated with the latest Landlab release version. The instructions page would points to this repo, with brief instructions (click the green Code button, select Download ZIP, unzip it, and voilá there are the notebooks). Pro: makes it relatively easy for users to download (just) the notebooks and place them in a convenient location. Con: adds an extra step to the release process (i.e., with each release, we would update the separate notebooks repo with a copy of all the notebooks in the release version).

@mcflugen or others, do you think the above diagnosis is correct? If so, any other ideas about how to make it easier for users to get the notebooks on to their computers in a a findable/accessible way?

**Comment by chronictectonic** [comment]
Thanks. 

Option 1 did not work. I did not find any folders named "notebooks" in my installation (on Windows 8) and the path you provided (or anything similar) was not found to exist.

Option 2 worked.

**Comment by chronictectonic** [comment]
I'm still having issues with this:

When I open the jupyter notebooks the input cells won't run and I get a kernel error.

I'm thinking it might be related to the organization of the directories again. I have placed the notebooks in the home directory where I run Anaconda.

The kernel error output is pasted below.
Thanks for your assistance

Traceback (most recent call last):
  File "c:\users\spa62678\anaconda3\envs\landlab_notebooks\lib\site-packages\tornado\web.py", line 1704, in _execute
    result = await result
  File "c:\users\spa62678\anaconda3\envs\landlab_notebooks\lib\site-packages\tornado\gen.py", line 769, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "c:\users\spa62678\anaconda3\envs\landlab_notebooks\lib\site-packages\notebook\services\sessions\handlers.py", line 69, in post
    model = yield maybe_future(
  File "c:\users\spa62678\anaconda3\envs\landlab_notebooks\lib\site-packages\tornado\gen.py", line 762, in run
    value = future.result()
  File "c:\users\spa62678\anaconda3\envs\landlab_notebooks\lib\site-packages\tornado\gen.py", line 769, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "c:\users\spa62678\anaconda3\envs\landlab_notebooks\lib\site-packages\notebook\services\sessions\sessionmanager.py", line 88, in create_session
    kernel_id = yield self.start_kernel_for_session(session_id, path, name, type, kernel_name)
  File "c:\users\spa62678\anaconda3\envs\landlab_notebooks\lib\site-packages\tornado\gen.py", line 762, in run
    value = future.result()
  File "c:\users\spa62678\anaconda3\envs\landlab_notebooks\lib\site-packages\tornado\gen.py", line 769, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "c:\users\spa62678\anaconda3\envs\landlab_notebooks\lib\site-packages\notebook\services\sessions\sessionmanager.py", line 100, in start_kernel_for_session
    kernel_id = yield maybe_future(
  File "c:\users\spa62678\anaconda3\envs\landlab_notebooks\lib\site-packages\tornado\gen.py", line 762, in run
    value = future.result()
  File "c:\users\spa62678\anaconda3\envs\landlab_notebooks\lib\site-packages\notebook\services\kernels\kernelmanager.py", line 176, in start_kernel
    kernel_id = await maybe_future(self.pinned_superclass.start_kernel(self, **kwargs))
  File "c:\users\spa62678\anaconda3\envs\landlab_notebooks\lib\site-packages\jupyter_client\multikernelmanager.py", line 185, in start_kernel
    km.start_kernel(**kwargs)
  File "c:\users\spa62678\anaconda3\envs\landlab_notebooks\lib\site-packages\jupyter_client\manager.py", line 309, in start_kernel
    kernel_cmd, kw = self.pre_start_kernel(**kw)
  File "c:\users\spa62678\anaconda3\envs\landlab_notebooks\lib\site-packages\jupyter_client\manager.py", line 258, in pre_start_kernel
    self.write_connection_file()
  File "c:\users\spa62678\anaconda3\envs\landlab_notebooks\lib\site-packages\jupyter_client\connect.py", line 468, in write_connection_file
    self.connection_file, cfg = write_connection_file(self.connection_file,
  File "c:\users\spa62678\anaconda3\envs\landlab_notebooks\lib\site-packages\jupyter_client\connect.py", line 138, in write_connection_file
    with secure_write(fname) as f:
  File "c:\users\spa62678\anaconda3\envs\landlab_notebooks\lib\contextlib.py", line 117, in __enter__
    return next(self.gen)
  File "c:\users\spa62678\anaconda3\envs\landlab_notebooks\lib\site-packages\jupyter_core\paths.py", line 461, in secure_write
    win32_restrict_file_to_user(fname)
  File "c:\users\spa62678\anaconda3\envs\landlab_notebooks\lib\site-packages\jupyter_core\paths.py", line 387, in win32_restrict_file_to_user
    import win32api
ImportError: DLL load failed while importing win32api: The specified module could not be found.

**Comment by mcflugen** [comment]
@chronictectonic

A couple of questions:
* Does this happen with all of the notebooks or just one or two in particular?
* It looks like you're on Windows, is that right?
* Are you able to run *any* notebooks or is it just the *landlab* notebooks?

I'll see if I can reproduce your error and how we might be able to get you up and running.

**Comment by chronictectonic** [comment]
Hi @mcflugen thanks for your response

It seems to happen with all of the _landlab_ notebooks and yes I'm on Windows.

I was able to run the FastScape demos for example just now without issue.

**Comment by gregtucker** [comment]
Note: turns out I was wrong about Option 1, in that the notebooks don't normally get added when you do a regular conda install of Landlab. They have to be downloaded separately (or else run remotely, e.g., on Binder or HydroShare or CSDMS' JupyterHub).

**Comment by mcflugen** [comment]
@chronictectonic It appears that this is an issue with the *win32api* package and *conda*. You can read more about it in the following issues: jupyter/notebook#4980 and jupyter/jupyter_core#215. There doesn't seem to be a great solution, unfortunately. There are a couple of workarounds described in those two issues, however. The most popular seems to be to run the following,
```bash
python [environment path]/Scripts/pywin32_postinstall.py -install
```
