### ISSUE TITLE
Litholayer: slows down during model run

### ISSUE THREAD

**Issue by valpedro** [landlab/landlab#1325]
Dear Landlab developers,

Thanks a lot for making LEMs more accessible and developing such an amazing tool. My knowledge of python and Landlab is not deep, so please keep that in mind as I describe my issue. 

I'm beginning to use the Litholayers component on some of my research. 

I've been modeling the exhumation of a 5-km band of resistant lithology at the middle to lower reach of a south-flowing only model. Right now, it's a vertical contact (a 5-km wall advecting upward).

I think I am setting the model up correctly (it does what I expect it to do), but the run slows down (a lot!) midrun and it makes me wonder if my setup is consuming more RAM than what is actually needed. The models start fast but as runtime goes on, more and more RAM is consumed (starts at <10% RAM e ramps up to >90% during the run, on a machine with 32Gb of memory and a 3.6GHZ (4.8GHZ OVERCLOCK) CPU) and the model slows down, eventually to 2 steps per minute or less. My grid is 500 x 500 with dx = 200m (so 100 km by 100 km with 200 m resolution). I tried applying this with a lower resolution and a higher resolution. The slow down still happens, but to smaller and greater degree, respectively. 

What I did:
1) First I ran a model using FastscapeEroder, LinearDiffuser, and FlowAccumulator until the model reached topographic equilibrium (or is close to it). This generates the file [BLU4_eq_lores_300000ky.txt](https://github.com/landlab/landlab/files/6978289/BLU4_eq_lores_300000ky.txt) which is the input file for the subsequent tests I run using LithoLayers. Here, I run it with a uniform K, call it K1. This is done using this .py file [BLU4_lores.txt](https://github.com/landlab/landlab/files/6978321/BLU4_lores.txt). BLU4_lores.py uses a noise file as input (starting_noise_lores.txt, [starting_noise_lores.txt](https://github.com/landlab/landlab/files/6978271/starting_noise_lores.txt))

2) In LithoLayer **what I think I'm doing** is: i) generate a litholayer component with arbitrary thicknesses; ii) advect it down a 1km with a uniform K (K1 in this case) but also with a 5 km wide band of lower K (e.g. 1/5 of K1) between y = 10 km and y = 15 km; iii) advect it down some more with uniform K (K1) so that I have some equilibrium time before the model exhumes the spatially variable lithology; iv) add the topography from BLU4_lores_3000000ky.txt and assign K1 to this topography. Then I run the model and export the topography and rock_id outputs every 100 timesteps. This part is done using [BLU4a.txt](https://github.com/landlab/landlab/files/6978332/BLU4a.txt).

Looking at the outputs in matlab, the model does exactly what I want it to do. However, the landlab run slows down significantly from a few timesteps per second in the beginning of the model run, to eventually 1 timestep per minute sometime around the 5000th timestep. Along with that, RAM ramps up and up and up, reaching 16+ Gb used. From what I can tell, the model continues to slow down as it goes.

Am I setting it up wrong? Am I inducing the slow down or is that just the way it is?
Any chance you can give me some feedback? I highly appreciate your help.

**Comment by kbarnhart** [comment]
@valpedro could you attach a .py file that doesn't have any external dependencies (e.g., doesn't require another file with input data) that shows these issues? I can take a look at that.

**Comment by valpedro** [comment]
Hi @kbarnhart
I'm glad you can take a look. 
I'm attaching the .py file as .txt (github doesn't let me upload a .py file for some reason) without any external dependencies. 
It is not exactly as I said in the first description (e.g. it's a lower resolution and does not use any input grid), but the slow down still happens. As configured, the spatially variable lithology is 4 km deep so until that amount is advected, it will have uniform lithology. 

Let me know if you need anything else from me. I appreciate your feedback. 
[test_PV.txt](https://github.com/landlab/landlab/files/6995070/test_PV.txt)

**Comment by kbarnhart** [comment]
will take a look, thanks for adding that example @valpedro 

it may be next week when I get to it.

**Comment by kbarnhart** [comment]
@valpedro a couple of early comments. Still playing around with this, and haven't yet run the model until the point where the resistant layer is exhumed... But I thought I'd let you know a few things I noticed:

1. For this application you probably want to use MaterialLayers instead of EventLayers as the basis for the LithoLayers component. Every time you erode with EventLayers you create a layer of zeros... which is probably what was causing the RAMM issues. Material layers takes a little while longer to initialize the first time (maybe a minute total) because it is doing some checking about layer combining, but it's not too much time compared with the simulation itself. 

    You can create an initial flat lying rock layer that is underneath your vertical layers with something like
`lith3 = LithoLayers(mg3, [10], [0],  layer_type='MaterialLayers', attrs=attrs)`

2.  You might consider initializing the simulation with a very very shallow slope to the south and using a depression finder. This makes it easier for flow routing to establish the drainage network through erosion and often makes it computationally faster. Including/not including a depression finder may or may not be what you are interested in depending on the specific scientific questions you are interested in. For example, it will force hydrologic connectivity between the area north of the resistant layer and the open boundary on the south. 
`fa3 = FlowAccumulator(mg3, flow_director="D8", depression_finder="DepressionFinderAndRouter")`

Will let you know if I find anything else of interest.

**Comment by kbarnhart** [comment]
OK. A few more things that may or may not solve your problem, but may be of interest.

I suspect that your original slowdown was due to using an EventLayer object to store the layers. This is why the RAM continues to grow. 

When I re-implement this with MaterialLayers, each timestep takes about 0.1 second on my computer, until the resistant layer emerges. RAM is stable. Once the resistant layer emerges many of the timesteps are just as fast as before, and occasionally I get slower timesteps of 15 seconds. The key thing to note is that with MaterialLayers you only get a new layer if what is deposited is different than what is below. This is nice because it means you reduce the layer object data volume, but it means you have to check whether what is deposited is the same as what is there or not. This is the timesink. Now, it only occurs if diffusion is on, because diffusion is the only way to get a deposit in this model.

It seems like there are a couple of ways around this:
1. Decide that simulations are fast enough with MaterialLayers & diffusion (fingers crossed this solves it for you).
2. Decide that you don't need diffusion
3. Try and make the comparison function in material layers faster (its defined at line 290 in the function is_compatible). I don't know how to make this faster. I just tried two ideas and they both made it slower 🤦 .
4. Something else. 

I'm going to ping @mcflugen here in case he has ideas on item (3) and because I suspect he'd be curious about this.

**Comment by kbarnhart** [comment]
And this is my current working version of your example (thanks!). The major modifications I've made to play around with it are 
1. exhume the resistant layer sooner
2. make the grid smaller in the x direction
3. change to material layers
4. use the profiler tools
5. use a depression finder. 

```python
# -*- coding: utf-8 -*-
"""
Created on Mon Aug 16 14:27:20 2021

@author: pedro
"""


import warnings
warnings.filterwarnings('ignore')

import os
import numpy as np

import matplotlib
import matplotlib.pyplot as plt


from landlab import RasterModelGrid
from landlab.components import FlowAccumulator, FastscapeEroder, LinearDiffuser, Lithology, LithoLayers
from landlab.plot import imshow_grid


import time

exhume_time = 10* 1000*1000
nts = 140000
dt = 1000
U = 0.00004


dx=400
mg3 = RasterModelGrid((250,100),dx)
z3 = mg3.add_zeros('node', 'topographic__elevation', units = 'm')
random_field = 0.01 * np.random.randn(mg3.size('node'))
z3 += random_field - random_field.min()


# to help drainage establish, start with a very slight tilt 
z3 += 0.0001 * mg3.y_of_node
mg3.set_closed_boundaries_at_grid_edges(True, True, True, False)

z0s = 10 * np.arange(-1, 2)  #dummy depths
z0s[-1] = 2 #dummy depths
z0s[-2] = 1 #dummy depths
z0s[-3] = 0 #dummy depths
ids = np.tile([0, 0, 0], 1) #same rocks
attrs = {'K_sp': {0: 5e-6, 1: 5e-7}} 

# start by creating the rock block better... make a super super steeply dipping layer. Then shove it under a big deposit. 

lith3 = LithoLayers(mg3, [10], [0],  layer_type='MaterialLayers', attrs=attrs)

spatially_variable_rock_id = mg3.ones('node')
spatially_variable_rock_id[mg3.y_of_node < 110000] = 0 #create rock type 0 everywhere
spatially_variable_rock_id[mg3.y_of_node < 30000] = 1 #set a lower reach with type 1 between 30 and 10 km
spatially_variable_rock_id[mg3.y_of_node < 10000] = 0 #set rock type 0 between 0 and 10 km
dz_ad =-1000. #advect the rocks down 1 km
lith3.dz_advection=dz_ad 
lith3.rock_id=spatially_variable_rock_id
lith3.run_one_step() #the spatially variable configuration is now between 0 and 1 km depth
# imshow_grid(mg3, 'K_sp')

spatially_variable_rock_id2 = mg3.ones('node')
spatially_variable_rock_id2[mg3.y_of_node < 110000] = 0
dz_ad = -U * exhume_time #advect the current rock configuration down 4 km in order to run the model to equilibrium for 100 Ma before exhuming spatially variable lithology
lith3.dz_advection=dz_ad
lith3.rock_id=spatially_variable_rock_id2
lith3.run_one_step() #now the rock configuration is uniform between 0 and 4 km depth and variable between 4 and 5 km depth
# imshow_grid(mg3, 'K_sp')

lith3.dz_advection=0
lith3.rock_id=0
lith3.run_one_step()
# imshow_grid(mg3, 'K_sp')



fa3 = FlowAccumulator(mg3, flow_director="D8", depression_finder="DepressionFinderAndRouter")
sp3 = FastscapeEroder(mg3, K_sp='K_sp', m_sp=0.45, n_sp=1)
ld3 = LinearDiffuser(mg3, linear_diffusivity=0.0025)

dur = []
z3max = []
zdiffmax = []
K_min = []

import cProfile, pstats, io
from pstats import SortKey
pr = cProfile.Profile()
pr.enable()

for i in range(nts):

    zinit = z3.copy()
    
    starttime = time.time()
    fa3.run_one_step()
    sp3.run_one_step(dt=dt)
    ld3.run_one_step(dt=dt)
    dz_ad2 = np.zeros(mg3.size('node'))
    dz_ad2[mg3.core_nodes] = U * dt
    z3 += dz_ad2
    lith3.dz_advection=dz_ad2
    lith3.rock_id=0 #deposited rocks are type 0
    lith3.run_one_step()

    
    # we are creating many layers. this is not what I'd expect to happen 
    # since the rock time shoudl be the same. 
    duration = time.time() - starttime
    dur.append(duration)
    
    # when do the hard rocks exume? Should be around 100,000 timesteps
    K_min.append(mg3.at_node["K_sp"].min())
    
    # hold onto some steady state assessment metrics
    zdiffm = np.max(np.abs(zinit-z3))
    zdiffmax.append(zdiffm)
    z3max.append(z3.max())
    print(i, lith3.dz.shape, np.round(duration,3), np.round(z3.max(), 1), np.round(zdiffm, 4), mg3.at_node["K_sp"].min())
    
    #if i > 100000:#save outputs after 100 Ma (presumably when the variable rocks start exhuming)
    #    if (i%100==0):
    #        imshow_grid(mg3, 'K_sp')
    #        np.savetxt('test_z'+str(i)+'ky.txt',mg3.at_node['topographic__elevation'])
    #        np.savetxt('test_rock'+str(i)+'ky.txt',mg3.at_node['rock_type__id'])
    
    # 100146 timestep when exhumed in the channels. 
    # Then it does take closer to 15 seconds per timestep instead of 0.01 s per timestep. 


# then it slows down when it needs to add another layer b/c of checking against. 
# it is all in material_layers function is_compatible.

# and you only get deposition with diffusion. If you have no diffusion... no deposition
# no issue. 

    
pr.disable()
s = io.StringIO()
sortby = SortKey.CUMULATIVE
ps = pstats.Stats(pr, stream=s).sort_stats(sortby)
ps.print_stats()
print(s.getvalue()[:1000])          
# imshow_grid(mg2, 'K_sp')
# imshow_grid(mg3, 'rock_type__id', cmap='viridis')
````

**Comment by valpedro** [comment]
Hi @kbarnhart, thanks so so much for your time and feedback. I did not know of these distinctions of Material vs Event layers, thanks for pointing it out. Will MaterialLayers still work if I want to model dipping layers (i.e. the resistant lithology dips southward)?

I'm now going to play around with what you suggested (and your working version) and let you know how it goes. Probably will be back later with more questions. Thanks again!

**Comment by kbarnhart** [comment]
@valpedro both Material and Event layers are equally capable of modeling dipping layers. Event layers was originally designed by @mcflugen for chronostratigraphy applications. This means that if you run `lith3.run_one_step()` and no deposition/erosion occurs a new layer of zeros will be added to the layer object, reflecting the timestep with no change. This means that if you have a domain that is 100x100, and you run it for 100 timesteps, the EventLayer object will end up with 1000000 elements in it.  

In contrast, Material Layers will only make a new layer if material gets deposited on it that is different from what has already been deposited. So if you set up the system as you have, you start with a layers object that has the shape (nnodes, 3) because your layers object has the first, lowest small layer, then the alternating resistant/less resistant layer, and then the thick layer used to come to steady state. Your layers object stays that same shape for many timesteps, until you start to exhume the resistant layer. At that point diffusion will place less resistant material into the channels made of more resistant material. It is only in that situation that MaterialLayers will create a new layer.

Hope that helps rather than being confusing. :)

**Comment by valpedro** [comment]
Hi @kbarnhart, this absolutely helps and I'm reassessing my approach based on your feedback. Thank you once again.

I'm playing around with your suggestions and it all worked well so I tried increasing the resolution back to my original plans (i.e. RasterModelGrid((500, 500), 200) ) and hit another memory problem. I get the attached error: 
![error_msg](https://user-images.githubusercontent.com/60072380/130471350-e433459b-cce5-4fe7-98a8-99c371ca5ee0.jpeg)

Is there a work around for this one?

**Comment by kbarnhart** [comment]
@valpedro that is a general python error indicating that you've asked python to allocate an array that is larger than your RAM, in this case 466 GB. I will admit I'm a little surprised by this error because I'd expect it to only need an array of shape (250000,) at this point. I don't have time to dig into this today, but will try to look into it sometime this week. 

Another thought you might consider. Do you need to update the lithology object every timestep? I suspect not, and that updating it with run_one_step only every 10 timesteps might be sufficient.

**Comment by valpedro** [comment]
The memory issue happens when I try to initiate litholayers using the MaterialLayers option. It does not happen if I use the other option, i.e. lith3 = LithoLayers(mg3, [1], [0], attrs=attrs).

I tested what grid size LithoLayers can handle using the MaterialLayers option. It varies by computer (less RAM, smaller grid) and as I get closer to the grid size limit of the computer (say... RasterModelGrid((200, 400), 200) ) I get this error (instead of getting the error I printed above): 

runfile('D:/Model_data/Pval_etal/testes/test_MaterialLayers_v2.py', wdir='D:/Model_data/Pval_etal/testes')
Traceback (most recent call last):
  File "D:\Model_data\Pval_etal\testes\test_MaterialLayers_v2.py", line 65, in <module>
    lith3.run_one_step() #the spatially variable configuration is now between 0 and 1 km depth
  File "C:\ProgramData\Anaconda3\lib\site-packages\landlab\components\lithology\lithology.py", line 995, in run_one_step
    self.add_layer(elevation_change, rock_id=self.rock_id)
  File "C:\ProgramData\Anaconda3\lib\site-packages\landlab\components\lithology\lithology.py", line 606, in add_layer
    self._layers.add(thickness, **attributes)
  File "C:\ProgramData\Anaconda3\lib\site-packages\landlab\layers\materiallayers.py", line 269, in add
    compatible = self.number_of_layers > 0 and self.is_compatible(dz, **kwds)
  File "C:\ProgramData\Anaconda3\lib\site-packages\landlab\layers\materiallayers.py", line 314, in is_compatible
    if not np.all(is_compatible[where_deposition]):
TypeError: 'bool' object is not subscriptable

..if I try a greater grid size, I get that other error. Not sure it helps but I thought I'd mention it just in case.

**Comment by valpedro** [comment]
About updating litholayers only every 10 timesteps. This suggestion might do it! I think you're right, with the low advection rates I'm using, I think 10 timesteps is okay. 

I went back to using EventLayers (since I was able to generate larger grids with it) and updating every 10 timesteps does not consume the RAM too quickly and allows me to reach longer timescales before running out of RAM, plus I can also go back to running linear diffusion as well. So, thanks for that suggestion!  

I'm still curious about the memory issue using MaterialLayers as it might be better in the long run.
