### ISSUE TITLE
Developer install from source problem

### ISSUE THREAD

**Issue by slundell123** [landlab/landlab#1330]
Hello,

I am working on adding a component to landlab and have been having issues installing my forked branch from source. The error I am getting happens when I try to create the conda environment. 

```
slundell@ubuntu:~/Documents/DLA/landlab$ conda env update --file=environment-dev.yml`
Collecting package metadata (repodata.json): done
Solving environment: done
Installing pip dependencies: - Ran pip subprocess with arguments:
['/home/slundell/anaconda3/envs/landlab_dev/bin/python', '-m', 'pip', 'install', '-U', '-r', '/home/slundell/Documents/DLA/landlab/condaenv.yylsuvif.requirements.txt']
Pip subprocess output:

Pip subprocess error:
WARNING: The directory '/home/slundell/.cache/pip' or its parent directory is not owned or is not writable by the current user. The cache has been disabled. Check the permissions and owner of that directory. If executing pip with sudo, you should use sudo's -H flag.
ERROR: Exception:
Traceback (most recent call last):
  File "/home/slundell/anaconda3/envs/landlab_dev/lib/python3.9/site-packages/pip/_internal/cli/base_command.py", line 173, in _main
    status = self.run(options, args)
  File "/home/slundell/anaconda3/envs/landlab_dev/lib/python3.9/site-packages/pip/_internal/cli/req_command.py", line 203, in wrapper
    return func(self, options, args)
  File "/home/slundell/anaconda3/envs/landlab_dev/lib/python3.9/site-packages/pip/_internal/commands/install.py", line 286, in run
    reqs = self.get_requirements(args, options, finder, session)
  File "/home/slundell/anaconda3/envs/landlab_dev/lib/python3.9/site-packages/pip/_internal/cli/req_command.py", line 384, in get_requirements
    for parsed_req in parse_requirements(
  File "/home/slundell/anaconda3/envs/landlab_dev/lib/python3.9/site-packages/pip/_internal/req/req_file.py", line 135, in parse_requirements
    for parsed_line in parser.parse(filename, constraint):
  File "/home/slundell/anaconda3/envs/landlab_dev/lib/python3.9/site-packages/pip/_internal/req/req_file.py", line 319, in parse
    yield from self._parse_and_recurse(filename, constraint)
  File "/home/slundell/anaconda3/envs/landlab_dev/lib/python3.9/site-packages/pip/_internal/req/req_file.py", line 348, in _parse_and_recurse
    yield from self._parse_and_recurse(req_path, nested_constraint)
  File "/home/slundell/anaconda3/envs/landlab_dev/lib/python3.9/site-packages/pip/_internal/req/req_file.py", line 324, in _parse_and_recurse
    for line in self._parse_file(filename, constraint):
  File "/home/slundell/anaconda3/envs/landlab_dev/lib/python3.9/site-packages/pip/_internal/req/req_file.py", line 353, in _parse_file
    _, content = get_file_content(filename, self._session)
  File "/home/slundell/anaconda3/envs/landlab_dev/lib/python3.9/site-packages/pip/_internal/req/req_file.py", line 518, in get_file_content
    resp = session.get(url)
  File "/home/slundell/anaconda3/envs/landlab_dev/lib/python3.9/site-packages/pip/_vendor/requests/sessions.py", line 555, in get
    return self.request('GET', url, **kwargs)
  File "/home/slundell/anaconda3/envs/landlab_dev/lib/python3.9/site-packages/pip/_internal/network/session.py", line 454, in request
    return super().request(method, url, *args, **kwargs)
  File "/home/slundell/anaconda3/envs/landlab_dev/lib/python3.9/site-packages/pip/_vendor/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/slundell/anaconda3/envs/landlab_dev/lib/python3.9/site-packages/pip/_vendor/requests/sessions.py", line 697, in send
    r.content
  File "/home/slundell/anaconda3/envs/landlab_dev/lib/python3.9/site-packages/pip/_vendor/requests/models.py", line 836, in content
    self._content = b''.join(self.iter_content(CONTENT_CHUNK_SIZE)) or b''
  File "/home/slundell/anaconda3/envs/landlab_dev/lib/python3.9/site-packages/pip/_vendor/requests/models.py", line 769, in generate
    chunk = self.raw.read(chunk_size)
AttributeError: 'FileNotFoundError' object has no attribute 'read'

failed

CondaEnvException: Pip failed
```

Any advice on if this is a problem with my local environment or one of the install files? 

I am running python 3.6.9

Thanks,
Sarah

**Comment by gregtucker** [comment]
Have you tried running this with `sudo`, i.e., `sudo conda env update --file=environment-dev.yml`?

**Comment by slundell123** [comment]
Yes, I have. The following is the output: 
```
slundell@ubuntu:~/Documents/DLA/landlab$ sudo conda env update --file=environment-dev.yml
sudo: conda: command not found
```

**Comment by SiccarPoint** [comment]
Hi Sarah - that last error looks suspiciously like a non-Landlab system setup problem to me. Couple of ideas:

1. Update conda just in case. This at least might provide more clarity on what's going on.
2. As the error recommends, check the permissions on that pip folder, and its parents. `ls -l` for the ouput you need, and look at the left-hand column. Assuming you have admin rights on your machine, I'd expect to see something like `dwrxr-xr-x` on the .conda directory and (??) `-rw-r--r--` on the executable... but I'm not sure why it's even looking at a cache to be honest.
3. Fully uninstall and reinstall `conda`, as I think that's where your problem is. (Sorry!)
4. Report back.

I've always been warned it can be super dicey to start using `sudo` too much with `pip` or `conda` - it can create unexpected and weird behaviour later. So don't get in the habit...

Also, you aren't running anything nonstandard in your terminal are you? (e.g., `zsh`?) I've had bad experiences with this...

Sometimes stuff like this can be related to what's in your `.bash_profile` or `.bashrc` (which depends on your OS). If one of these exists, take a look at it in a text editor and make sure any links related to conda or python are pointed at somewhere that makes sense. In particular, check you don't have some links pointed at the "system" Python and some at Conda.

**Comment by mcflugen** [comment]
@slundell123 I believe the problem is that the newest versions of *pip* don't like our *environment-dev.yml* file—in particular, the `file:<relative_path>` part. *pip* now expects *file:* followed by an absolute path or just a relative path without the *file:* prefix. Try changing your *environment-dev.yml* file to look like,

```yaml
name: landlab_dev
dependencies:
- pip
- pip:
  - -r requirements.txt
  - -r requirements-testing.txt
  - -r requirements-dev.txt
  - -r requirements-notebooks.txt
  - -r requirements-docs.txt
```

We'll update our environment files to fix this but, in the meantime, if you could try the above fix and get back to us with your results, that would be super!

**Comment by slundell123** [comment]
@mcflugen That worked. Thank you!
