### ISSUE TITLE
Landlab installation error

### ISSUE THREAD

**Issue by t190403098** [landlab/landlab#1391]
Hello,

I followed the instruction `https://landlab.readthedocs.io/en/master/development/install/install.html#install` to install Landlab. But I get an error of `subprocess-exited-with-error` while I run the `pip install -e .`

I worked on Python 3.9 on windows.

The detail of the error is as follows: 

```
(landlab) C:\Users\tian\anaconda3\envs\landlab-master>pip install -e .
Obtaining file:///C:/Users/tian/anaconda3/envs/landlab-master
  Installing build dependencies ... done
  Checking if build backend supports build_editable ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: netcdf4 in c:\users\tian\anaconda3\envs\landlab\lib\site-packages (from landlab==2.4.2.dev0) (1.5.8)
Requirement already satisfied: pyyaml in c:\users\tian\anaconda3\envs\landlab\lib\site-packages (from landlab==2.4.2.dev0) (6.0)
Requirement already satisfied: scipy in c:\users\tian\anaconda3\envs\landlab\lib\site-packages (from landlab==2.4.2.dev0) (1.8.0)
Requirement already satisfied: pandas in c:\users\tian\anaconda3\envs\landlab\lib\site-packages (from landlab==2.4.2.dev0) (1.4.1)
Requirement already satisfied: matplotlib in c:\users\tian\anaconda3\envs\landlab\lib\site-packages (from landlab==2.4.2.dev0) (3.5.1)
Requirement already satisfied: bmipy in c:\users\tian\anaconda3\envs\landlab\lib\site-packages (from landlab==2.4.2.dev0) (2.0)
Requirement already satisfied: numpy in c:\users\tian\anaconda3\envs\landlab\lib\site-packages (from landlab==2.4.2.dev0) (1.22.2)
Requirement already satisfied: pyshp in c:\users\tian\anaconda3\envs\landlab\lib\site-packages (from landlab==2.4.2.dev0) (2.2.0)
Requirement already satisfied: richdem in c:\users\tian\anaconda3\envs\landlab\lib\site-packages (from landlab==2.4.2.dev0) (2.3.0)
Requirement already satisfied: xarray>=0.16 in c:\users\tian\anaconda3\envs\landlab\lib\site-packages (from landlab==2.4.2.dev0) (0.21.1)
Requirement already satisfied: statsmodels in c:\users\tian\anaconda3\envs\landlab\lib\site-packages (from landlab==2.4.2.dev0) (0.13.2)
Requirement already satisfied: packaging>=20.0 in c:\users\tian\anaconda3\envs\landlab\lib\site-packages (from xarray>=0.16->landlab==2.4.2.dev0) (21.3)
Requirement already satisfied: python-dateutil>=2.8.1 in c:\users\tian\anaconda3\envs\landlab\lib\site-packages (from pandas->landlab==2.4.2.dev0) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in c:\users\tian\anaconda3\envs\landlab\lib\site-packages (from pandas->landlab==2.4.2.dev0) (2021.3)
Requirement already satisfied: black in c:\users\tian\anaconda3\envs\landlab\lib\site-packages (from bmipy->landlab==2.4.2.dev0) (22.1.0)
Requirement already satisfied: jinja2 in c:\users\tian\anaconda3\envs\landlab\lib\site-packages (from bmipy->landlab==2.4.2.dev0) (3.0.3)
Requirement already satisfied: click in c:\users\tian\anaconda3\envs\landlab\lib\site-packages (from bmipy->landlab==2.4.2.dev0) (8.0.3)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\tian\anaconda3\envs\landlab\lib\site-packages (from matplotlib->landlab==2.4.2.dev0) (4.29.1)
Requirement already satisfied: pillow>=6.2.0 in c:\users\tian\anaconda3\envs\landlab\lib\site-packages (from matplotlib->landlab==2.4.2.dev0) (9.0.1)
Requirement already satisfied: pyparsing>=2.2.1 in c:\users\tian\anaconda3\envs\landlab\lib\site-packages (from matplotlib->landlab==2.4.2.dev0) (3.0.7)
Requirement already satisfied: kiwisolver>=1.0.1 in c:\users\tian\anaconda3\envs\landlab\lib\site-packages (from matplotlib->landlab==2.4.2.dev0) (1.3.2)
Requirement already satisfied: cycler>=0.10 in c:\users\tian\anaconda3\envs\landlab\lib\site-packages (from matplotlib->landlab==2.4.2.dev0) (0.11.0)
Requirement already satisfied: cftime in c:\users\tian\anaconda3\envs\landlab\lib\site-packages (from netcdf4->landlab==2.4.2.dev0) (1.5.2)
Requirement already satisfied: patsy>=0.5.2 in c:\users\tian\anaconda3\envs\landlab\lib\site-packages (from statsmodels->landlab==2.4.2.dev0) (0.5.2)
Requirement already satisfied: six in c:\users\tian\anaconda3\envs\landlab\lib\site-packages (from patsy>=0.5.2->statsmodels->landlab==2.4.2.dev0) (1.16.0)
Requirement already satisfied: platformdirs>=2 in c:\users\tian\anaconda3\envs\landlab\lib\site-packages (from black->bmipy->landlab==2.4.2.dev0) (2.5.0)
Requirement already satisfied: mypy-extensions>=0.4.3 in c:\users\tian\anaconda3\envs\landlab\lib\site-packages (from black->bmipy->landlab==2.4.2.dev0) (0.4.3)
Requirement already satisfied: tomli>=1.1.0 in c:\users\tian\anaconda3\envs\landlab\lib\site-packages (from black->bmipy->landlab==2.4.2.dev0) (2.0.1)
Requirement already satisfied: pathspec>=0.9.0 in c:\users\tian\anaconda3\envs\landlab\lib\site-packages (from black->bmipy->landlab==2.4.2.dev0) (0.9.0)
Requirement already satisfied: typing-extensions>=3.10.0.0 in c:\users\tian\anaconda3\envs\landlab\lib\site-packages (from black->bmipy->landlab==2.4.2.dev0) (4.1.1)
Requirement already satisfied: colorama in c:\users\tian\anaconda3\envs\landlab\lib\site-packages (from click->bmipy->landlab==2.4.2.dev0) (0.4.4)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\tian\anaconda3\envs\landlab\lib\site-packages (from jinja2->bmipy->landlab==2.4.2.dev0) (2.0.1)
Installing collected packages: landlab
  Running setup.py develop for landlab
    error: subprocess-exited-with-error

    × python setup.py develop did not run successfully.
    │ exit code: 1
    ╰─> [114 lines of output]
        running develop
        C:\Users\tian\AppData\Local\Temp\pip-build-env-mnhb2drp\overlay\Lib\site-packages\setuptools\command\easy_install.py:160: EasyInstallDeprecationWarning: easy_install command is deprecated. Use build and pip and other standards-based tools.
          warnings.warn(
        C:\Users\tian\AppData\Local\Temp\pip-build-env-mnhb2drp\overlay\Lib\site-packages\setuptools\command\install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
          warnings.warn(
        running egg_info
        writing landlab.egg-info\PKG-INFO
        writing dependency_links to landlab.egg-info\dependency_links.txt
        writing entry points to landlab.egg-info\entry_points.txt
        writing requirements to landlab.egg-info\requires.txt
        writing top-level names to landlab.egg-info\top_level.txt
        reading manifest file 'landlab.egg-info\SOURCES.txt'
        reading manifest template 'MANIFEST.in'
        warning: no previously-included files found matching '.codeclimate.yml'
        warning: no previously-included files found matching '.gitmodules'
        warning: no previously-included files found matching '.landscape.yaml'
        warning: no previously-included files found matching '.readthedocs.yaml'
        warning: no previously-included files found matching 'conftest.py'
        warning: no previously-included files found matching 'CONTRIBUTING.md'
        warning: no previously-included files found matching 'environment*yml'
        warning: no previously-included files found matching '.pre-commit-config.yaml'
        warning: no previously-included files matching '*' found under directory 'joss'
        warning: no previously-included files matching '*' found under directory 'notebooks'
        warning: no previously-included files matching '*py' found under directory 'scripts'
        warning: no previously-included files matching '*sh' found under directory 'scripts'
        adding license file 'LICENSE.txt'
        adding license file 'AUTHORS.rst'
        running build_ext
        skipping 'landlab\ca\cfuncs.c' Cython extension (up-to-date)
        skipping 'landlab\components\bedrock_landslider\cfuncs.c' Cython extension (up-to-date)
        skipping 'landlab\components\depression_finder\cfuncs.c' Cython extension (up-to-date)
        skipping 'landlab\components\drainage_density\cfuncs.c' Cython extension (up-to-date)
        skipping 'landlab\components\erosion_deposition\cfuncs.c' Cython extension (up-to-date)
        skipping 'landlab\components\flexure\cfuncs.c' Cython extension (up-to-date)
        skipping 'landlab\components\flexure\ext\flexure1d.c' Cython extension (up-to-date)
        skipping 'landlab\components\flow_accum\cfuncs.c' Cython extension (up-to-date)
        skipping 'landlab\components\flow_director\cfuncs.c' Cython extension (up-to-date)
        skipping 'landlab\components\overland_flow\_neighbors_at_link.c' Cython extension (up-to-date)
        skipping 'landlab\components\priority_flood_flow_router\cfuncs.c' Cython extension (up-to-date)
        skipping 'landlab\components\space\ext\calc_qs.c' Cython extension (up-to-date)
        skipping 'landlab\components\space\ext\calc_sequential_ero_depo.c' Cython extension (up-to-date)
        skipping 'landlab\components\stream_power\cfuncs.c' Cython extension (up-to-date)
        skipping 'landlab\graph\cfuncs.c' Cython extension (up-to-date)
        skipping 'landlab\graph\hex\ext\hex.c' Cython extension (up-to-date)
        skipping 'landlab\graph\hex\ext\perimeternodes.c' Cython extension (up-to-date)
        skipping 'landlab\graph\matrix\ext\at_patch.c' Cython extension (up-to-date)
        skipping 'landlab\graph\matrix\ext\matrix.c' Cython extension (up-to-date)
        skipping 'landlab\graph\object\ext\at_node.c' Cython extension (up-to-date)
        skipping 'landlab\graph\object\ext\at_patch.c' Cython extension (up-to-date)
        skipping 'landlab\graph\quantity\ext\of_link.c' Cython extension (up-to-date)
        skipping 'landlab\graph\quantity\ext\of_patch.c' Cython extension (up-to-date)
        skipping 'landlab\graph\sort\ext\argsort.c' Cython extension (up-to-date)
        skipping 'landlab\graph\sort\ext\remap_element.c' Cython extension (up-to-date)
        skipping 'landlab\graph\sort\ext\spoke_sort.c' Cython extension (up-to-date)
        skipping 'landlab\graph\structured_quad\ext\at_cell.c' Cython extension (up-to-date)
        skipping 'landlab\graph\structured_quad\ext\at_face.c' Cython extension (up-to-date)
        skipping 'landlab\graph\structured_quad\ext\at_link.c' Cython extension (up-to-date)
        skipping 'landlab\graph\structured_quad\ext\at_node.c' Cython extension (up-to-date)
        skipping 'landlab\graph\structured_quad\ext\at_patch.c' Cython extension (up-to-date)
        skipping 'landlab\graph\voronoi\ext\delaunay.c' Cython extension (up-to-date)
        skipping 'landlab\graph\voronoi\ext\voronoi.c' Cython extension (up-to-date)
        skipping 'landlab\grid\cfuncs.c' Cython extension (up-to-date)
        skipping 'landlab\layers\ext\eventlayers.c' Cython extension (up-to-date)
        skipping 'landlab\utils\_matrix.c' Cython extension (up-to-date)
        skipping 'landlab\utils\ext\jaggedarray.c' Cython extension (up-to-date)
        building 'landlab.ca.cfuncs' extension
        Traceback (most recent call last):
          File "<string>", line 2, in <module>
          File "<pip-setuptools-caller>", line 34, in <module>
          File "C:\Users\tian\anaconda3\envs\landlab-master\setup.py", line 64, in <module>
            setup(
          File "C:\Users\tian\AppData\Local\Temp\pip-build-env-mnhb2drp\overlay\Lib\site-packages\setuptools\__init__.py", line 155, in setup
            return distutils.core.setup(**attrs)
          File "C:\Users\tian\AppData\Local\Temp\pip-build-env-mnhb2drp\overlay\Lib\site-packages\setuptools\_distutils\core.py", line 148, in setup
            return run_commands(dist)
          File "C:\Users\tian\AppData\Local\Temp\pip-build-env-mnhb2drp\overlay\Lib\site-packages\setuptools\_distutils\core.py", line 163, in run_commands
            dist.run_commands()
          File "C:\Users\tian\AppData\Local\Temp\pip-build-env-mnhb2drp\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 967, in run_commands
            self.run_command(cmd)
          File "C:\Users\tian\AppData\Local\Temp\pip-build-env-mnhb2drp\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 986, in run_command
            cmd_obj.run()
          File "C:\Users\tian\AppData\Local\Temp\pip-build-env-mnhb2drp\overlay\Lib\site-packages\setuptools\command\develop.py", line 34, in run
            self.install_for_development()
          File "C:\Users\tian\AppData\Local\Temp\pip-build-env-mnhb2drp\overlay\Lib\site-packages\setuptools\command\develop.py", line 114, in install_for_development
            self.run_command('build_ext')
          File "C:\Users\tian\AppData\Local\Temp\pip-build-env-mnhb2drp\overlay\Lib\site-packages\setuptools\_distutils\cmd.py", line 313, in run_command
            self.distribution.run_command(command)
          File "C:\Users\tian\AppData\Local\Temp\pip-build-env-mnhb2drp\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 986, in run_command
            cmd_obj.run()
          File "C:\Users\tian\AppData\Local\Temp\pip-build-env-mnhb2drp\overlay\Lib\site-packages\setuptools\command\build_ext.py", line 79, in run
            _build_ext.run(self)
          File "C:\Users\tian\AppData\Local\Temp\pip-build-env-mnhb2drp\overlay\Lib\site-packages\Cython\Distutils\old_build_ext.py", line 186, in run
            _build_ext.build_ext.run(self)
          File "C:\Users\tian\AppData\Local\Temp\pip-build-env-mnhb2drp\overlay\Lib\site-packages\setuptools\_distutils\command\build_ext.py", line 339, in run
            self.build_extensions()
          File "C:\Users\tian\AppData\Local\Temp\pip-build-env-mnhb2drp\overlay\Lib\site-packages\Cython\Distutils\old_build_ext.py", line 195, in build_extensions
            _build_ext.build_ext.build_extensions(self)
          File "C:\Users\tian\AppData\Local\Temp\pip-build-env-mnhb2drp\overlay\Lib\site-packages\setuptools\_distutils\command\build_ext.py", line 448, in build_extensions
            self._build_extensions_serial()
          File "C:\Users\tian\AppData\Local\Temp\pip-build-env-mnhb2drp\overlay\Lib\site-packages\setuptools\_distutils\command\build_ext.py", line 473, in _build_extensions_serial
            self.build_extension(ext)
          File "C:\Users\tian\AppData\Local\Temp\pip-build-env-mnhb2drp\overlay\Lib\site-packages\setuptools\command\build_ext.py", line 202, in build_extension
            _build_ext.build_extension(self, ext)
          File "C:\Users\tian\AppData\Local\Temp\pip-build-env-mnhb2drp\overlay\Lib\site-packages\setuptools\_distutils\command\build_ext.py", line 528, in build_extension
            objects = self.compiler.compile(sources,
          File "C:\Users\tian\AppData\Local\Temp\pip-build-env-mnhb2drp\overlay\Lib\site-packages\setuptools\_distutils\_msvccompiler.py", line 327, in compile
            self.initialize()
          File "C:\Users\tian\AppData\Local\Temp\pip-build-env-mnhb2drp\overlay\Lib\site-packages\setuptools\_distutils\_msvccompiler.py", line 224, in initialize
            vc_env = _get_vc_env(plat_spec)
          File "C:\Users\tian\AppData\Local\Temp\pip-build-env-mnhb2drp\overlay\Lib\site-packages\setuptools\msvc.py", line 316, in msvc14_get_vc_env
            return _msvc14_get_vc_env(plat_spec)
          File "C:\Users\tian\AppData\Local\Temp\pip-build-env-mnhb2drp\overlay\Lib\site-packages\setuptools\msvc.py", line 270, in _msvc14_get_vc_env
            raise distutils.errors.DistutilsPlatformError(
        setuptools._distutils.errors.DistutilsPlatformError: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
        [end of output]

    note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× python setup.py develop did not run successfully.
│ exit code: 1
╰─> [114 lines of output]
    running develop
    C:\Users\tian\AppData\Local\Temp\pip-build-env-mnhb2drp\overlay\Lib\site-packages\setuptools\command\easy_install.py:160: EasyInstallDeprecationWarning: easy_install command is deprecated. Use build and pip and other standards-based tools.
      warnings.warn(
    C:\Users\tian\AppData\Local\Temp\pip-build-env-mnhb2drp\overlay\Lib\site-packages\setuptools\command\install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
      warnings.warn(
    running egg_info
    writing landlab.egg-info\PKG-INFO
    writing dependency_links to landlab.egg-info\dependency_links.txt
    writing entry points to landlab.egg-info\entry_points.txt
    writing requirements to landlab.egg-info\requires.txt
    writing top-level names to landlab.egg-info\top_level.txt
    reading manifest file 'landlab.egg-info\SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    warning: no previously-included files found matching '.codeclimate.yml'
    warning: no previously-included files found matching '.gitmodules'
    warning: no previously-included files found matching '.landscape.yaml'
    warning: no previously-included files found matching '.readthedocs.yaml'
    warning: no previously-included files found matching 'conftest.py'
    warning: no previously-included files found matching 'CONTRIBUTING.md'
    warning: no previously-included files found matching 'environment*yml'
    warning: no previously-included files found matching '.pre-commit-config.yaml'
    warning: no previously-included files matching '*' found under directory 'joss'
    warning: no previously-included files matching '*' found under directory 'notebooks'
    warning: no previously-included files matching '*py' found under directory 'scripts'
    warning: no previously-included files matching '*sh' found under directory 'scripts'
    adding license file 'LICENSE.txt'
    adding license file 'AUTHORS.rst'
    running build_ext
    skipping 'landlab\ca\cfuncs.c' Cython extension (up-to-date)
    skipping 'landlab\components\bedrock_landslider\cfuncs.c' Cython extension (up-to-date)
    skipping 'landlab\components\depression_finder\cfuncs.c' Cython extension (up-to-date)
    skipping 'landlab\components\drainage_density\cfuncs.c' Cython extension (up-to-date)
    skipping 'landlab\components\erosion_deposition\cfuncs.c' Cython extension (up-to-date)
    skipping 'landlab\components\flexure\cfuncs.c' Cython extension (up-to-date)
    skipping 'landlab\components\flexure\ext\flexure1d.c' Cython extension (up-to-date)
    skipping 'landlab\components\flow_accum\cfuncs.c' Cython extension (up-to-date)
    skipping 'landlab\components\flow_director\cfuncs.c' Cython extension (up-to-date)
    skipping 'landlab\components\overland_flow\_neighbors_at_link.c' Cython extension (up-to-date)
    skipping 'landlab\components\priority_flood_flow_router\cfuncs.c' Cython extension (up-to-date)
    skipping 'landlab\components\space\ext\calc_qs.c' Cython extension (up-to-date)
    skipping 'landlab\components\space\ext\calc_sequential_ero_depo.c' Cython extension (up-to-date)
    skipping 'landlab\components\stream_power\cfuncs.c' Cython extension (up-to-date)
    skipping 'landlab\graph\cfuncs.c' Cython extension (up-to-date)
    skipping 'landlab\graph\hex\ext\hex.c' Cython extension (up-to-date)
    skipping 'landlab\graph\hex\ext\perimeternodes.c' Cython extension (up-to-date)
    skipping 'landlab\graph\matrix\ext\at_patch.c' Cython extension (up-to-date)
    skipping 'landlab\graph\matrix\ext\matrix.c' Cython extension (up-to-date)
    skipping 'landlab\graph\object\ext\at_node.c' Cython extension (up-to-date)
    skipping 'landlab\graph\object\ext\at_patch.c' Cython extension (up-to-date)
    skipping 'landlab\graph\quantity\ext\of_link.c' Cython extension (up-to-date)
    skipping 'landlab\graph\quantity\ext\of_patch.c' Cython extension (up-to-date)
    skipping 'landlab\graph\sort\ext\argsort.c' Cython extension (up-to-date)
    skipping 'landlab\graph\sort\ext\remap_element.c' Cython extension (up-to-date)
    skipping 'landlab\graph\sort\ext\spoke_sort.c' Cython extension (up-to-date)
    skipping 'landlab\graph\structured_quad\ext\at_cell.c' Cython extension (up-to-date)
    skipping 'landlab\graph\structured_quad\ext\at_face.c' Cython extension (up-to-date)
    skipping 'landlab\graph\structured_quad\ext\at_link.c' Cython extension (up-to-date)
    skipping 'landlab\graph\structured_quad\ext\at_node.c' Cython extension (up-to-date)
    skipping 'landlab\graph\structured_quad\ext\at_patch.c' Cython extension (up-to-date)
    skipping 'landlab\graph\voronoi\ext\delaunay.c' Cython extension (up-to-date)
    skipping 'landlab\graph\voronoi\ext\voronoi.c' Cython extension (up-to-date)
    skipping 'landlab\grid\cfuncs.c' Cython extension (up-to-date)
    skipping 'landlab\layers\ext\eventlayers.c' Cython extension (up-to-date)
    skipping 'landlab\utils\_matrix.c' Cython extension (up-to-date)
    skipping 'landlab\utils\ext\jaggedarray.c' Cython extension (up-to-date)
    building 'landlab.ca.cfuncs' extension
    Traceback (most recent call last):
      File "<string>", line 2, in <module>
      File "<pip-setuptools-caller>", line 34, in <module>
      File "C:\Users\tian\anaconda3\envs\landlab-master\setup.py", line 64, in <module>
        setup(
      File "C:\Users\tian\AppData\Local\Temp\pip-build-env-mnhb2drp\overlay\Lib\site-packages\setuptools\__init__.py", line 155, in setup
        return distutils.core.setup(**attrs)
      File "C:\Users\tian\AppData\Local\Temp\pip-build-env-mnhb2drp\overlay\Lib\site-packages\setuptools\_distutils\core.py", line 148, in setup
        return run_commands(dist)
      File "C:\Users\tian\AppData\Local\Temp\pip-build-env-mnhb2drp\overlay\Lib\site-packages\setuptools\_distutils\core.py", line 163, in run_commands
        dist.run_commands()
      File "C:\Users\tian\AppData\Local\Temp\pip-build-env-mnhb2drp\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 967, in run_commands
        self.run_command(cmd)
      File "C:\Users\tian\AppData\Local\Temp\pip-build-env-mnhb2drp\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 986, in run_command
        cmd_obj.run()
      File "C:\Users\tian\AppData\Local\Temp\pip-build-env-mnhb2drp\overlay\Lib\site-packages\setuptools\command\develop.py", line 34, in run
        self.install_for_development()
      File "C:\Users\tian\AppData\Local\Temp\pip-build-env-mnhb2drp\overlay\Lib\site-packages\setuptools\command\develop.py", line 114, in install_for_development
        self.run_command('build_ext')
      File "C:\Users\tian\AppData\Local\Temp\pip-build-env-mnhb2drp\overlay\Lib\site-packages\setuptools\_distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "C:\Users\tian\AppData\Local\Temp\pip-build-env-mnhb2drp\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 986, in run_command
        cmd_obj.run()
      File "C:\Users\tian\AppData\Local\Temp\pip-build-env-mnhb2drp\overlay\Lib\site-packages\setuptools\command\build_ext.py", line 79, in run
        _build_ext.run(self)
      File "C:\Users\tian\AppData\Local\Temp\pip-build-env-mnhb2drp\overlay\Lib\site-packages\Cython\Distutils\old_build_ext.py", line 186, in run
        _build_ext.build_ext.run(self)
      File "C:\Users\tian\AppData\Local\Temp\pip-build-env-mnhb2drp\overlay\Lib\site-packages\setuptools\_distutils\command\build_ext.py", line 339, in run
        self.build_extensions()
      File "C:\Users\tian\AppData\Local\Temp\pip-build-env-mnhb2drp\overlay\Lib\site-packages\Cython\Distutils\old_build_ext.py", line 195, in build_extensions
        _build_ext.build_ext.build_extensions(self)
      File "C:\Users\tian\AppData\Local\Temp\pip-build-env-mnhb2drp\overlay\Lib\site-packages\setuptools\_distutils\command\build_ext.py", line 448, in build_extensions
        self._build_extensions_serial()
      File "C:\Users\tian\AppData\Local\Temp\pip-build-env-mnhb2drp\overlay\Lib\site-packages\setuptools\_distutils\command\build_ext.py", line 473, in _build_extensions_serial
        self.build_extension(ext)
      File "C:\Users\tian\AppData\Local\Temp\pip-build-env-mnhb2drp\overlay\Lib\site-packages\setuptools\command\build_ext.py", line 202, in build_extension
        _build_ext.build_extension(self, ext)
      File "C:\Users\tian\AppData\Local\Temp\pip-build-env-mnhb2drp\overlay\Lib\site-packages\setuptools\_distutils\command\build_ext.py", line 528, in build_extension
        objects = self.compiler.compile(sources,
      File "C:\Users\tian\AppData\Local\Temp\pip-build-env-mnhb2drp\overlay\Lib\site-packages\setuptools\_distutils\_msvccompiler.py", line 327, in compile
        self.initialize()
      File "C:\Users\tian\AppData\Local\Temp\pip-build-env-mnhb2drp\overlay\Lib\site-packages\setuptools\_distutils\_msvccompiler.py", line 224, in initialize
        vc_env = _get_vc_env(plat_spec)
      File "C:\Users\tian\AppData\Local\Temp\pip-build-env-mnhb2drp\overlay\Lib\site-packages\setuptools\msvc.py", line 316, in msvc14_get_vc_env
        return _msvc14_get_vc_env(plat_spec)
      File "C:\Users\tian\AppData\Local\Temp\pip-build-env-mnhb2drp\overlay\Lib\site-packages\setuptools\msvc.py", line 270, in _msvc14_get_vc_env
        raise distutils.errors.DistutilsPlatformError(
    setuptools._distutils.errors.DistutilsPlatformError: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
    [end of output]

note: This error originates from a subprocess, and is likely not a problem with pip.
```

Sorry for the long text. 

Any idea or advice on solving the problem?

Thanks in advance.

**Comment by t190403098** [comment]
Thanks for your time. After installing the Microsoft Visual C++, the error above was solved.
