### ISSUE TITLE
write netCDF files error 

### ISSUE THREAD

**Issue by taranguiz** [landlab/landlab#1511]
Hi all! 

I have been trying to generate NetCDF files to visualize in Paraview from the outputs of every time step while I'm using the following geomorphic components over a Raster model grid:

- Exponential Weatherer
- Depth DependentTaylorDiffuser
- PriorityFloodFlowRouter
- SpaceLargeScaleEroder

I'm using the documentation for write_raster_netcdf (https://landlab.readthedocs.io/en/master/reference/io/netcdf.html) and my error comes when **I do not specify the names of the fields** that I want to include in the netcdf file. So before the loop, I do the following:

1. I read my grid which contains the following fields:

['topographic__elevation', 'soil__depth', 'bedrock__elevation', 'soil_production__rate', 'water__unit_flux_in', 'flow__link_to_receiver_node', 'drainage_area', 'flood_status_code', 'flow__upstream_node_order', 'flow__receiver_node', 'surface_water__discharge', 'topographic__steepest_slope', 'flow__receiver_proportions', 'depression_free_elevation', 'squared_length_adjacent', 'sediment__flux']

2. initialize the components: 

3. Run the loop:
```
while time < total_model_time:

      z[mg.core_nodes]+= (uplift_rate*dt) #do uplift all the time
      bed[mg.core_nodes]+= (uplift_rate*dt) #this is bedrock
      expweath.calc_soil_prod_rate()
      ddtd.run_one_step(dt)
      fr.run_one_step()
      space.run_one_step(dt)
      if time%100 == 0:
          write_raster_netcdf('topo_%s_yrs.nc' %(int(time + dt)),mg, format="NETCDF3_64BIT") 
```
       
 The error is the following:

```
Traceback (most recent call last):
  File "/Users/taranguiz/Research/Lateral_advection/geomorph_dynamics_loop.py", line 260, in <module>
    write_raster_netcdf('topo_%s_yrs.nc' %(int(time + dt)),mg, format="NETCDF3_64BIT") 
  File "/Users/taranguiz/opt/anaconda3/envs/erosion/lib/python3.9/site-packages/landlab/io/netcdf/write.py", line 823, in write_raster_netcdf
    return write_netcdf(
  File "/Users/taranguiz/opt/anaconda3/envs/erosion/lib/python3.9/site-packages/landlab/io/netcdf/write.py", line 707, in write_netcdf
    dataset = xr.Dataset(data, attrs=attrs)
  File "/Users/taranguiz/opt/anaconda3/envs/erosion/lib/python3.9/site-packages/xarray/core/dataset.py", line 754, in __init__
    variables, coord_names, dims, indexes, _ = merge_data_and_coords(
  File "/Users/taranguiz/opt/anaconda3/envs/erosion/lib/python3.9/site-packages/xarray/core/merge.py", line 484, in merge_data_and_coords
    return merge_core(
  File "/Users/taranguiz/opt/anaconda3/envs/erosion/lib/python3.9/site-packages/xarray/core/merge.py", line 640, in merge_core
    dims = calculate_dimensions(variables)
  File "/Users/taranguiz/opt/anaconda3/envs/erosion/lib/python3.9/site-packages/xarray/core/dataset.py", line 208, in calculate_dimensions
    raise ValueError(
ValueError: conflicting sizes for dimension 'nt': length 8 on 'squared_length_adjacent' and length 1 on {'ni': 'x', 'nj': 'y', 'nt': 'topographic__elevation'}

```

So then, I tried specifying a couple of parameters.  The code didn't break and I got my NetCDF files with all the variables that I specified.
```
write_raster_netcdf(f'topo_{int(time+dt)}_yrs.nc', mg, format="NETCDF3_64BIT",
                              names=['surface_water__discharge', 'drainage_area',
                                     'bedrock__elevation', 'soil__depth',
                                     'sediment__flux', 'soil_production__rate'])

```

I'm just reporting this issue because I don't understand the error with 'squared_leght_adjacent and 'topographic__elevation' .

Thanks, I hope it was clear enough for you to understand :) 
Best,

**Comment by gregtucker** [comment]
@BCampforts will know for sure, but my guess is that `squared_length_adjacent` is a 2D array (# nodes x 8). The solution, as you discovered, is to omit that field from the output. In my experience, it is generally good practice to name the fields you want to write, as some components create fields that are not especially useful for visualizing, and there is no point taking up file space or memory space with these.

Note that you can get animations easily in paraview if you number your netcdf files sequentially, for example foo000.nc, foo001.nc, etc. Paraview will assume these represent a sequence of frames.
