### ISSUE TITLE
write_netcdf/ write_raster_netcdf/ grid.save(file.nc) permission denied

### ISSUE THREAD

**Issue by taranguiz** [landlab/landlab#1817]
Hi there! I have been trying to save output grids of some runs as netcdf files but I have not been successful recently. I did not have this problem before and I'm not sure if is something on the new version of landlab or what it could be. I'm using frontier (jupyter hub) and using the CSDMS kernell/environment that should be the most updated landlab! 

This is what I have in the code:
write_raster_netcdf(
        f'/home/jupyter-taranguiz/StrikeSlip/climate/output_topo/{model_name}/{model_name}final-topo.nc', 
        mg, 
        format='NETCDF4', 
        names=[
            'bedrock__elevation',
            'drainage_area',
            'flood_status_code',
            'flow__link_to_receiver_node',
            'flow__receiver_node',
            'flow__receiver_proportions',
            'flow__upstream_node_order',
            'soil__depth',
            'soil_production__rate',
            'surface_water__discharge',
            'topographic__elevation',
            'topographic__steepest_slope',
            'water__unit_flux_in'
        ]
    )

I tend to get these errors: 

  File "/opt/tljh/user/envs/csdms/lib/python3.11/site-packages/xarray/backends/file_manager.py", line 210, in _acquire_with_cache_info
    file = self._cache[self._key]
           ~~~~~~~~~~~^^^^^^^^^^^
  File "/opt/tljh/user/envs/csdms/lib/python3.11/site-packages/xarray/backends/lru_cache.py", line 56, in __getitem__
    value = self._cache[key]
            ~~~~~~~~~~~^^^^^
KeyError: [<class 'netCDF4._netCDF4.Dataset'>, ('/home/jupyter-taranguiz/StrikeSlip/climate/output_topo/test_nov/test_novfinal-topo.nc',), 'a', (('clobber', True), ('diskless', False), ('format', 'NETCDF4'), ('persist', False)), '08934859-cdf7-4dd6-94b4-e8df2015b323']

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jupyter-taranguiz/StrikeSlip/climate/geomorph_dynamics_loop_trying_something.py", line 355, in <module>
    write_raster_netcdf(
  File "/opt/tljh/user/envs/csdms/lib/python3.11/site-packages/landlab/io/netcdf/write.py", line 825, in write_raster_netcdf
    return write_netcdf(
           ^^^^^^^^^^^^^
  File "/opt/tljh/user/envs/csdms/lib/python3.11/site-packages/landlab/io/netcdf/write.py", line 712, in write_netcdf
    dataset.to_netcdf(path, mode="w", format=format, unlimited_dims=("nt",))
  File "/opt/tljh/user/envs/csdms/lib/python3.11/site-packages/xarray/core/dataset.py", line 1946, in to_netcdf
    return to_netcdf(  # type: ignore  # mypy cannot resolve the overloads:(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/tljh/user/envs/csdms/lib/python3.11/site-packages/xarray/backends/api.py", line 1255, in to_netcdf
    store = store_open(target, mode, format, group, **kwargs)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/tljh/user/envs/csdms/lib/python3.11/site-packages/xarray/backends/netCDF4_.py", line 389, in open
    return cls(manager, group=group, mode=mode, lock=lock, autoclose=autoclose)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/tljh/user/envs/csdms/lib/python3.11/site-packages/xarray/backends/netCDF4_.py", line 336, in __init__
    self.format = self.ds.data_model
                  ^^^^^^^
  File "/opt/tljh/user/envs/csdms/lib/python3.11/site-packages/xarray/backends/netCDF4_.py", line 398, in ds
    return self._acquire()
           ^^^^^^^^^^^^^^^
  File "/opt/tljh/user/envs/csdms/lib/python3.11/site-packages/xarray/backends/netCDF4_.py", line 392, in _acquire
    with self._manager.acquire_context(needs_lock) as root:
  File "/opt/tljh/user/envs/csdms/lib/python3.11/contextlib.py", line 137, in __enter__
    return next(self.gen)
           ^^^^^^^^^^^^^^
  File "/opt/tljh/user/envs/csdms/lib/python3.11/site-packages/xarray/backends/file_manager.py", line 198, in acquire_context
    file, cached = self._acquire_with_cache_info(needs_lock)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/tljh/user/envs/csdms/lib/python3.11/site-packages/xarray/backends/file_manager.py", line 216, in _acquire_with_cache_info
    file = self._opener(*self._args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "src/netCDF4/_netCDF4.pyx", line 2449, in netCDF4._netCDF4.Dataset.__init__
  File "src/netCDF4/_netCDF4.pyx", line 2012, in netCDF4._netCDF4._ensure_nc_success
PermissionError: [Errno 13] Permission denied: '/home/jupyter-taranguiz/StrikeSlip/climate/output_topo/test_nov/test_novfinal-topo.nc'


Really appreciate your help! Best,
Tamara

**Comment by mcflugen** [comment]
@taranguiz could you please provided a [minimum reproducible example](https://en.wikipedia.org/wiki/Minimal_reproducible_example) so that I can try to reproduce your error? The ``PermissionError`` suggests to me that it may have something to do with the machine you are running on. Maybe the disk is full?
