### ISSUE TITLE
Problem with developer install

### ISSUE THREAD

**Issue by gregtucker** [landlab/landlab#1954]
Following the Developer Install instructions [here](https://landlab.readthedocs.io/en/latest/install/index.html) leads to the following:

```
(base) cu-biot-seec1-172:Landlab gtucker$ conda create --name landlab-dev
Channels:
 - conda-forge
 - defaults
Platform: osx-64
Collecting package metadata (repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: /Applications/anaconda3/envs/landlab-dev



Proceed ([y]/n)? y

Preparing transaction: done
Verifying transaction: done
Executing transaction: done
#
# To activate this environment, use
#
#     $ conda activate landlab-dev
#
# To deactivate an active environment, use
#
#     $ conda deactivate

(base) cu-biot-seec1-172:Landlab gtucker$ conda activate landlab-dev
(landlab-dev) cu-biot-seec1-172:Landlab gtucker$ git clone https://github.com/landlab/landlab.git
Cloning into 'landlab'...
remote: Enumerating objects: 76799, done.
remote: Counting objects: 100% (3678/3678), done.
remote: Compressing objects: 100% (1694/1694), done.
remote: Total 76799 (delta 2347), reused 3091 (delta 1946), pack-reused 73121
Receiving objects: 100% (76799/76799), 282.36 MiB | 53.06 MiB/s, done.
Resolving deltas: 100% (56601/56601), done.
Updating files: 100% (1252/1252), done.

(landlab-dev) cu-biot-seec1-172:Landlab gtucker$ cd landlab
(landlab-dev) cu-biot-seec1-172:landlab gtucker$ conda install --file=requirements.in -c nodefaults -c conda-forge --override-channels

CondaValueError: could not parse 'importlib-resources; python_version < '3.12'' in: requirements.in

```

(system = Mac OS 14.5)

**Comment by mcflugen** [comment]
@gregtucker Use,
```python
pip install -e .
```
rather than `conda install`.

**Comment by mcflugen** [comment]
We should still support *conda* installs, though. Unfortunately, *conda* doesn't understand *pip* requirements files so we may have to have different instructions if someone would like to install all of *Landlab*'s dependencies with *conda*.

**Comment by gregtucker** [comment]
Ok, thanks. New issue: update the Dev Install instructions page to remove conda/mamba.

Meanwhile:

```
(landlab-dev) cu-biot-seec1-172:landlab gtucker$ pip install -e .
Obtaining file:///Users/gtucker/Dev/Landlab/landlab
  Installing build dependencies ... done
  Checking if build backend supports build_editable ... done
  Getting requirements to build editable ... done
  Preparing editable metadata (pyproject.toml) ... done
```

(...lots of stuff skipped...)

```
      clang -fno-strict-overflow -DNDEBUG -O2 -Wall -fPIC -O2 -isystem /Applications/anaconda3/envs/landlab-dev/include -fPIC -O2 -isystem /Applications/anaconda3/envs/landlab-dev/include -I/private/var/folders/r1/8sz6r01s2yj06sxwxwcl3m340000gn/T/pip-build-env-a7_1d0jh/overlay/lib/python3.12/site-packages/numpy/core/include -I/Applications/anaconda3/envs/landlab-dev/include/python3.12 -I/Applications/anaconda3/envs/landlab-dev/include/python3.12 -c landlab/ca/cfuncs.c -o /var/folders/r1/8sz6r01s2yj06sxwxwcl3m340000gn/T/tmpi6fuxrmv.build-temp/landlab/ca/cfuncs.o -fopenmp
      clang: error: unsupported option '-fopenmp'
      Traceback (most recent call last):
        File "/private/var/folders/r1/8sz6r01s2yj06sxwxwcl3m340000gn/T/pip-build-env-a7_1d0jh/overlay/lib/python3.12/site-packages/setuptools/_distutils/spawn.py", line 71, in spawn
          subprocess.check_call(cmd, env=_inject_macos_ver(env))
        File "/Applications/anaconda3/envs/landlab-dev/lib/python3.12/subprocess.py", line 413, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['/usr/bin/clang', '-fno-strict-overflow', '-DNDEBUG', '-O2', '-Wall', '-fPIC', '-O2', '-isystem', '/Applications/anaconda3/envs/landlab-dev/include', '-fPIC', '-O2', '-isystem', '/Applications/anaconda3/envs/landlab-dev/include', '-I/private/var/folders/r1/8sz6r01s2yj06sxwxwcl3m340000gn/T/pip-build-env-a7_1d0jh/overlay/lib/python3.12/site-packages/numpy/core/include', '-I/Applications/anaconda3/envs/landlab-dev/include/python3.12', '-I/Applications/anaconda3/envs/landlab-dev/include/python3.12', '-c', 'landlab/ca/cfuncs.c', '-o', '/var/folders/r1/8sz6r01s2yj06sxwxwcl3m340000gn/T/tmpi6fuxrmv.build-temp/landlab/ca/cfuncs.o', '-fopenmp']' returned non-zero exit status 1.
      
      The above exception was the direct cause of the following exception:
      
      Traceback (most recent call last):
        File "/private/var/folders/r1/8sz6r01s2yj06sxwxwcl3m340000gn/T/pip-build-env-a7_1d0jh/overlay/lib/python3.12/site-packages/setuptools/_distutils/unixccompiler.py", line 191, in _compile
          self.spawn(compiler_so + cc_args + [src, '-o', obj] + extra_postargs)
        File "/private/var/folders/r1/8sz6r01s2yj06sxwxwcl3m340000gn/T/pip-build-env-a7_1d0jh/overlay/lib/python3.12/site-packages/setuptools/_distutils/ccompiler.py", line 1044, in spawn
          spawn(cmd, dry_run=self.dry_run, **kwargs)
        File "/private/var/folders/r1/8sz6r01s2yj06sxwxwcl3m340000gn/T/pip-build-env-a7_1d0jh/overlay/lib/python3.12/site-packages/setuptools/_distutils/spawn.py", line 77, in spawn
          raise DistutilsExecError(
      distutils.errors.DistutilsExecError: command '/usr/bin/clang' failed with exit code 1
      
      During handling of the above exception, another exception occurred:
      
      Traceback (most recent call last):
        File "/private/var/folders/r1/8sz6r01s2yj06sxwxwcl3m340000gn/T/pip-build-env-a7_1d0jh/overlay/lib/python3.12/site-packages/setuptools/command/editable_wheel.py", line 153, in run
          self._create_wheel_file(bdist_wheel)
        File "/private/var/folders/r1/8sz6r01s2yj06sxwxwcl3m340000gn/T/pip-build-env-a7_1d0jh/overlay/lib/python3.12/site-packages/setuptools/command/editable_wheel.py", line 355, in _create_wheel_file
          files, mapping = self._run_build_commands(dist_name, unpacked, lib, tmp)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/r1/8sz6r01s2yj06sxwxwcl3m340000gn/T/pip-build-env-a7_1d0jh/overlay/lib/python3.12/site-packages/setuptools/command/editable_wheel.py", line 278, in _run_build_commands
          self._run_build_subcommands()
        File "/private/var/folders/r1/8sz6r01s2yj06sxwxwcl3m340000gn/T/pip-build-env-a7_1d0jh/overlay/lib/python3.12/site-packages/setuptools/command/editable_wheel.py", line 305, in _run_build_subcommands
          self.run_command(name)
        File "/private/var/folders/r1/8sz6r01s2yj06sxwxwcl3m340000gn/T/pip-build-env-a7_1d0jh/overlay/lib/python3.12/site-packages/setuptools/_distutils/cmd.py", line 316, in run_command
          self.distribution.run_command(command)
        File "/private/var/folders/r1/8sz6r01s2yj06sxwxwcl3m340000gn/T/pip-build-env-a7_1d0jh/overlay/lib/python3.12/site-packages/setuptools/dist.py", line 974, in run_command
          super().run_command(command)
        File "/private/var/folders/r1/8sz6r01s2yj06sxwxwcl3m340000gn/T/pip-build-env-a7_1d0jh/overlay/lib/python3.12/site-packages/setuptools/_distutils/dist.py", line 989, in run_command
          cmd_obj.run()
        File "/private/var/folders/r1/8sz6r01s2yj06sxwxwcl3m340000gn/T/pip-build-env-a7_1d0jh/overlay/lib/python3.12/site-packages/setuptools/command/build_ext.py", line 93, in run
          _build_ext.run(self)
        File "/private/var/folders/r1/8sz6r01s2yj06sxwxwcl3m340000gn/T/pip-build-env-a7_1d0jh/overlay/lib/python3.12/site-packages/setuptools/_distutils/command/build_ext.py", line 359, in run
          self.build_extensions()
        File "/private/var/folders/r1/8sz6r01s2yj06sxwxwcl3m340000gn/T/pip-build-env-a7_1d0jh/overlay/lib/python3.12/site-packages/setuptools/_distutils/command/build_ext.py", line 479, in build_extensions
          self._build_extensions_serial()
        File "/private/var/folders/r1/8sz6r01s2yj06sxwxwcl3m340000gn/T/pip-build-env-a7_1d0jh/overlay/lib/python3.12/site-packages/setuptools/_distutils/command/build_ext.py", line 505, in _build_extensions_serial
          self.build_extension(ext)
        File "/private/var/folders/r1/8sz6r01s2yj06sxwxwcl3m340000gn/T/pip-build-env-a7_1d0jh/overlay/lib/python3.12/site-packages/setuptools/command/build_ext.py", line 254, in build_extension
          _build_ext.build_extension(self, ext)
        File "/private/var/folders/r1/8sz6r01s2yj06sxwxwcl3m340000gn/T/pip-build-env-a7_1d0jh/overlay/lib/python3.12/site-packages/Cython/Distutils/build_ext.py", line 135, in build_extension
          super(build_ext, self).build_extension(ext)
        File "/private/var/folders/r1/8sz6r01s2yj06sxwxwcl3m340000gn/T/pip-build-env-a7_1d0jh/overlay/lib/python3.12/site-packages/setuptools/_distutils/command/build_ext.py", line 560, in build_extension
          objects = self.compiler.compile(
                    ^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/r1/8sz6r01s2yj06sxwxwcl3m340000gn/T/pip-build-env-a7_1d0jh/overlay/lib/python3.12/site-packages/setuptools/_distutils/ccompiler.py", line 605, in compile
          self._compile(obj, src, ext, cc_args, extra_postargs, pp_opts)
        File "/private/var/folders/r1/8sz6r01s2yj06sxwxwcl3m340000gn/T/pip-build-env-a7_1d0jh/overlay/lib/python3.12/site-packages/setuptools/_distutils/unixccompiler.py", line 193, in _compile
          raise CompileError(msg)
      distutils.errors.CompileError: command '/usr/bin/clang' failed with exit code 1
      /private/var/folders/r1/8sz6r01s2yj06sxwxwcl3m340000gn/T/pip-build-env-a7_1d0jh/overlay/lib/python3.12/site-packages/setuptools/_distutils/dist.py:989: _DebuggingTips: Problem in editable installation.
      !!
      
              ********************************************************************************
              An error happened while installing `landlab` in editable mode.
      
              The following steps are recommended to help debug this problem:
      
              - Try to install the project normally, without using the editable mode.
                Does the error still persist?
                (If it does, try fixing the problem before attempting the editable mode).
              - If you are using binary extensions, make sure you have all OS-level
                dependencies installed (e.g. compilers, toolchains, binary libraries, ...).
              - Try the latest version of setuptools (maybe the error was already fixed).
              - If you (or your project dependencies) are using any setuptools extension
                or customization, make sure they support the editable mode.
      
              After following the steps above, if the problem still persists and
              you think this is related to how setuptools handles editable installations,
              please submit a reproducible example
              (see https://stackoverflow.com/help/minimal-reproducible-example) to:
      
                  https://github.com/pypa/setuptools/issues
      
              See https://setuptools.pypa.io/en/latest/userguide/development_mode.html for details.
              ********************************************************************************
      
      !!
        cmd_obj.run()
      error: command '/usr/bin/clang' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building editable for landlab
Failed to build landlab
ERROR: Could not build wheels for landlab, which is required to install pyproject.toml-based projects
```

**Comment by gregtucker** [comment]
BUT probably compilers just need to be installed first...

**Comment by mcflugen** [comment]
> BUT probably compilers just need to be installed first...

Yes, that's likely the case.

I changed the default to be to build *Landlab* with openmp enabled, but that requires a compiler that understands the `-fopenmp` flag, which `/usr/bin/clang` does not. `conda install cxx-compiler` should fix this error.

**Comment by gregtucker** [comment]
Yup, confirmed, just needed to install compilers first.

**Comment by amanaster2** [comment]
Glad I found this issue; I was also following the dev install page and ran into the same thing @gregtucker did, but installing compilers and running `pip install -e .` worked.

**Comment by acatlett8** [comment]
so I'm not sure if this should be a different issue or not but i'm having problems when i try the command
mamba install --file=requirements.in -c nodefaults -c conda-forge --override-channels

I get the following error
could not parse 'importlib-resources; python_version < '3.12'' in: requirements.in

CondaValueError: could not parse 'importlib-resources; python_version < '3.12'' in: requirements.in

**Comment by mcflugen** [comment]
@acatlett8 This is the same issue. If you're ok with installing from *PyPI*, try the above solution (i.e. `pip install -e .`). If you would like to install from *conda-forge*, remove the bit after the semicolon and try again. That is, in `requirements.in` change
```
importlib-resources; python_version < '3.12'
```
to
```
importlib-resources
```
Thanks for the reminder that I still need to come up with a solution for this!

**Comment by acatlett8** [comment]
@mcflugen thanks! i was like it seemed similar but wasn't sure.

**Comment by pfeiffea** [comment]
@mcflugen I think I found a new issue here. I'm following the Developer Install instructions for conda [here](https://landlab.csdms.io/install/index.html) . 

- minor issue A: missing a return after `cd landlab `

- minor issue B: typos (?) in code for installing dependencies. What I see is: 
`conda install –file=requirements.in -c nodefaults -c conda-forge –override-channels`
but this yields an `unrecognized arguments` error

If I edit to what @gregtucker has above: 
`conda install --file=requirements.in -c nodefaults -c conda-forge --override-channels` 
it runs fine. 

I suspect this is just some autocorrect from a double dash to an em dash.. but it had me confused for a while.

**Comment by mcflugen** [comment]
@pfeiffea Thanks for reporting! The issue is actually just a markdown formatting error—instead of formatting those lines as code, they were treated as though they were regular text. #2155 should fix this.

**Comment by mcflugen** [comment]
> At the moment I still don't have a working developer install of landlab...

Oh no!

Please describe the steps you took to install Landlab. For example, the following
works for me:
```bash
git clone git@github.com:landlab/landlab landlab
cd landlab/
conda create -n landlab --yes
conda activate landlab
conda install compilers python=3.11 --yes
pip install -e .
```

**Comment by DavidLitwin** [comment]
Before I had used:
```
git clone https://github.com/DavidLitwin/landlab.git
cd landlab
conda create -n landlab_dev python=3.11
conda activate landlab_dev 
```
And then the two options I list in my comment above.

I just followed your procedure, and the install proceeds without issue. However, when I open a python console in that environment and try to run something, I get the following error. It seems that there's an issue with having both the `Users/dlitwin/landlab/src/` and `/Users/dlitwin/anaconda3/envs/landlab_dev/lib` in sys.path? How do I resolve this? 
```
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
Cell In[2], line 9
      6 from tqdm import tqdm
      7 import matplotlib.pyplot as plt
----> 9 from landlab import RasterModelGrid
     10 from landlab.components import (
     11     FastscapeEroder, 
     12     FlowAccumulator,
   (...)     16     LithoLayers,
     17 )
     19 # from virtual_karst_funcs import *

File ~/landlab/src/landlab/__init__.py:20
     18 from landlab.core.utils import ExampleData
     19 from landlab.field.errors import FieldError
---> 20 from landlab.grid.base import ModelGrid
     21 from landlab.grid.create import create_grid
     22 from landlab.grid.framed_voronoi import FramedVoronoiGrid

File ~/landlab/src/landlab/grid/__init__.py:1
----> 1 from landlab.grid.base import ModelGrid
      2 from landlab.grid.create import create_grid
      3 from landlab.grid.framed_voronoi import FramedVoronoiGrid

File ~/landlab/src/landlab/grid/base.py:12
      9 import numpy as np
     10 import xarray as xr
---> 12 from landlab.utils.decorators import make_return_array_immutable
     14 from ..core import load_params
     15 from ..core.utils import add_module_functions_to_class

File ~/landlab/src/landlab/utils/__init__.py:5
      3 from .add_halo import add_halo
      4 from .count_repeats import count_repeated_values
----> 5 from .matrix import get_core_node_at_node
      6 from .matrix import get_core_node_matrix
      7 from .return_array import return_array_at_link

File ~/landlab/src/landlab/utils/matrix.py:7
      4 import numpy as np
      5 from scipy.sparse import csc_matrix
----> 7 from ._matrix import fill_right_hand_side
      8 from ._matrix import get_matrix_diagonal_elements
      9 from ._matrix import get_matrix_diagonal_elements_with_coef

ImportError: dlopen(/Users/dlitwin/landlab/src/landlab/utils/_matrix.cpython-311-darwin.so, 0x0002): tried: '/Users/dlitwin/landlab/src/landlab/utils/_matrix.cpython-311-darwin.so' (duplicate LC_RPATH '/Users/dlitwin/anaconda3/envs/landlab_dev/lib'), '/System/Volumes/Preboot/Cryptexes/OS/Users/dlitwin/landlab/src/landlab/utils/_matrix.cpython-311-darwin.so' (no such file), '/Users/dlitwin/landlab/src/landlab/utils/_matrix.cpython-311-darwin.so' (duplicate LC_RPATH '/Users/dlitwin/anaconda3/envs/landlab_dev/lib')
```

**Comment by mcflugen** [comment]
When you started Python, do you start it from the command line or do you run Python through an IDE like Spyder? Do you still see the import error if you try to import landlab from the command line using the following,

```bash
conda activate landlab_dev
python -c 'import landlab; print(landlab.__version__)'
```
For me, this prints,
```
2.9.2.dev0
```

This last time, did you start with a clean working environment? It could be that one or more of the extension modules in your landlab folder is left over from a previous build and needs to be rebuilt. You my need to remove all of the shared libraries in your source folder and recompile. You could do this by trashing your landlab folder and rebuilding, or if you don't want to be that extreme, try running,
```bash
pip install nox
nox -s clean
```
and then running the build commands again.

**Comment by DavidLitwin** [comment]
OK, a fresh download of the folder from git finally did the trick, with the instructions you provided. It would be great to have those in the docs!
