### ISSUE TITLE
linear diffuser on VoronoiDelaunayGrid

### ISSUE THREAD

**Issue by hjgray10** [landlab/landlab#346]
Hello,

Sometimes when I run LinearDiffuser on a VoronoiDelaunayGrid, I get the following error. Other times, its works perfectly fine. I have to run the code once or twice to get a successful run.

Traceback (most recent call last):

  File "<ipython-input-150-ff54e4298694>", line 1, in <module>
    runfile('/home/harrison/SAFSHEAR/Voronoi/SAFSHEAR_Voronoi_V1.py', wdir='/home/harrison/SAFSHEAR/Voronoi')

  File "/home/harrison/anaconda/lib/python2.7/site-packages/spyderlib/widgets/externalshell/sitecustomize.py", line 699, in runfile
    execfile(filename, namespace)

  File "/home/harrison/anaconda/lib/python2.7/site-packages/spyderlib/widgets/externalshell/sitecustomize.py", line 81, in execfile
    builtins.execfile(filename, *where)

  File "/home/harrison/SAFSHEAR/Voronoi/SAFSHEAR_Voronoi_V1.py", line 56, in <module>
    lin_diffuse.run_one_step(dt) # diffuse terrain

  File "/home/harrison/anaconda/lib/python2.7/site-packages/landlab/components/diffusion/diffusion.py", line 287, in run_one_step
    self.diffuse(dt, **kwds)

  File "/home/harrison/anaconda/lib/python2.7/site-packages/landlab/components/diffusion/diffusion.py", line 255, in diffuse
    self.dqsds = self.grid.calc_flux_div_at_node(self.qs)

  File "/home/harrison/anaconda/lib/python2.7/site-packages/landlab/utils/decorators.py", line 178, in _wrapped
    return func(grid, vals, *args, **kwds)

  File "/home/harrison/anaconda/lib/python2.7/site-packages/landlab/grid/divergence.py", line 80, in calc_flux_div_at_node
    unit_flux[grid.link_at_face]) \

  File "/home/harrison/anaconda/lib/python2.7/site-packages/landlab/utils/decorators.py", line 178, in _wrapped
    return func(grid, vals, *args, **kwds)

  File "/home/harrison/anaconda/lib/python2.7/site-packages/landlab/grid/divergence.py", line 239, in _calc_net_face_flux_at_cell
    fac = grid.faces_at_cell

  File "/home/harrison/anaconda/lib/python2.7/site-packages/landlab/grid/base.py", line 2260, in faces_at_cell
    self._create_faces_at_cell()

  File "/home/harrison/anaconda/lib/python2.7/site-packages/landlab/grid/base.py", line 2321, in _create_faces_at_cell
    self._sort_faces_at_cell_by_angle()

  File "/home/harrison/anaconda/lib/python2.7/site-packages/landlab/grid/base.py", line 2291, in _sort_faces_at_cell_by_angle
    sorted_links]

ValueError: could not broadcast input array from shape (10) into shape (9).

**Comment by SiccarPoint** [comment]
For the record, this is actively impairing Harrison's work flow.

The issue appears to be related to there being some (only) configurations of A Voronoi that break the assumptions of `_sort_faces_at_cell_by_angle`. This is probably a thing where there's a mismatch between the mappings of nodes, links, cells, and faces. (i.e., occasionally a cell gets created been though one of its faces actually doesn't exist, or something like that).

This probably needs the attention of @gregtucker (because he designed the voronoi structures) or @mcflugen (because graph stuff, again).

**Comment by hjgray10** [comment]
Additionally, Sometimes when linear diffuser runs in a for loop, this error appears:

runfile('/home/harrison/SAFSHEAR/Voronoi/SAFSHEAR_Voronoi_V2.py', wdir='/home/harrison/SAFSHEAR/Voronoi')
start for loop
Traceback (most recent call last):

  File "<ipython-input-33-5ca0d974c16c>", line 1, in <module>
    runfile('/home/harrison/SAFSHEAR/Voronoi/SAFSHEAR_Voronoi_V2.py', wdir='/home/harrison/SAFSHEAR/Voronoi')

  File "/home/harrison/anaconda/lib/python2.7/site-packages/spyderlib/widgets/externalshell/sitecustomize.py", line 699, in runfile
    execfile(filename, namespace)

  File "/home/harrison/anaconda/lib/python2.7/site-packages/spyderlib/widgets/externalshell/sitecustomize.py", line 81, in execfile
    builtins.execfile(filename, *where)

  File "/home/harrison/SAFSHEAR/Voronoi/SAFSHEAR_Voronoi_V2.py", line 87, in <module>
    lin_diffuse.run_one_step(dt) # diffuse terrain

  File "/home/harrison/anaconda/lib/python2.7/site-packages/landlab/components/diffusion/diffusion.py", line 561, in run_one_step
    self.diffuse(dt, **kwds)

  File "/home/harrison/anaconda/lib/python2.7/site-packages/landlab/components/diffusion/diffusion.py", line 451, in diffuse
    mg.calc_flux_div_at_node(self.qs, out=self.dqsds)

  File "/home/harrison/anaconda/lib/python2.7/site-packages/landlab/utils/decorators.py", line 178, in _wrapped
    return func(grid, vals, *args, **kwds)

  File "/home/harrison/anaconda/lib/python2.7/site-packages/landlab/grid/divergence.py", line 80, in calc_flux_div_at_node
    unit_flux[grid.link_at_face]) \

IndexError: index 4636074041422070058 is out of bounds for axis 1 with size 5979
