### ISSUE TITLE
DepressionFinderAndRouter

### ISSUE THREAD

**Issue by hjgray10** [landlab/landlab#353]
Hi!

I have encountered a problem with DepressionFinderAndRouter when running a basic landscape evolution model:

`Traceback (most recent call last):

  File "<ipython-input-22-4108de105135>", line 1, in <module>
    runfile('/home/harrison/SAFSHEAR/Raster/Lake_fill_problem.py', wdir='/home/harrison/SAFSHEAR/Raster')

  File "/home/harrison/anaconda/lib/python2.7/site-packages/spyderlib/widgets/externalshell/sitecustomize.py", line 699, in runfile
    execfile(filename, namespace)

  File "/home/harrison/anaconda/lib/python2.7/site-packages/spyderlib/widgets/externalshell/sitecustomize.py", line 81, in execfile
    builtins.execfile(filename, *where)

  File "/home/harrison/SAFSHEAR/Raster/Lake_fill_problem.py", line 78, in <module>
    DepressionFinderAndRouter.map_depressions(fill)

  File "/home/harrison/anaconda/lib/python2.7/site-packages/landlab/components/flow_routing/lake_mapper.py", line 641, in map_depressions
    self._identify_depressions_and_outlets()

  File "/home/harrison/anaconda/lib/python2.7/site-packages/landlab/components/flow_routing/lake_mapper.py", line 557, in _identify_depressions_and_outlets
    self.find_depression_from_pit(pit_node)

  File "/home/harrison/anaconda/lib/python2.7/site-packages/landlab/components/flow_routing/lake_mapper.py", line 534, in find_depression_from_pit
    assert (count < max_count), 'too many iterations in lake filler!'

AssertionError: too many iterations in lake filler!`

This happens when the value of "K" in the stream power eroder is too small. I have attached a .txt with my code that recreates the problem. Increasing the value of K within the code from 0.1 to 1 seems to eliminate the issue. However, I need to be able to model these lower K values.

Cheers and thanks,

Harrison
[Lake_fill_problem.txt](https://github.com/landlab/landlab/files/342410/Lake_fill_problem.txt)

**Comment by hjgray10** [comment]
Thanks to Greg Tucker for fixing this!

**Comment by SiccarPoint** [comment]
I also made a few general improvements to this on Saturday night, subsequent to Greg's elimination of the major bug. This was mainly ensuring all fields get updated, especially `flow__link_to_receiver_node`, and a bit of speed optimisation.

Make sure you get them too!

**Comment by hjgray10** [comment]
Thanks Dan!!!
