### ISSUE TITLE
installation

### ISSUE THREAD

**Issue by hojjatseyyedi1982** [landlab/landlab#45]
I am trying to install Landlab for the first time but I am getting the following error:
"Traceback (most recent call last):
  File "<pyshell#18>", line 1, in <module>
    from setup.py import install
  File "C:\Flash Flood\landlab\landlab-master\setup.py", line 10, in <module>
    from landlab import **version**
  File "C:\Flash Flood\landlab\landlab-master\landlab__init__.py", line 45, in <module>
    from .testing.nosetester import LandlabTester
  File "C:\Flash Flood\landlab\landlab-master\landlab\testing\nosetester.py", line 3, in <module>
    import nose
ImportError: No module named nose"

Any comments why I am getting the error? How can I solve it?

Thanks and regards

**Comment by mdpiper** [comment]
Landlab has moved to `pytest` for testing, so `nose` is no longer a requirement.
