### ISSUE TITLE
problem with stream power when n < 1

### ISSUE THREAD

**Issue by nicgaspar** [landlab/landlab#475]
I know this just came up with @awickert. I'm sure I have the most recent version of the code and looked at the issues (#431, #444, #433) Dan cited for Andy. @SiccarPoint point told Andy that it was solved with issue #433. I checked what happened with that, and it seems @gregtucker added some code to fix an infinite look in the cfuncs.  But the fix is kicking me out because of that solution.  To be fair, if that solution wasn't there, then I'd run into an infinite loop.

More details below. Anyway, just asking in case it spurs something for @gregtucker or @SiccarPoint because they know this code well. Is it that I need to run a sink filler for this to work? The problem is definitely a flat slope.

Important code lines:

fr = FlowRouter(mg, method='D4')
sp = FastscapeEroder(mg, K_sp=0.00005, m_sp=0.4, n_sp=0.8, threshold_sp=0.,
                    rainfall_intensity=1.)
fr.run_one_step()
sp.run_one_step(dt)

What happens:

  warnings.warn(_use_error_msg)
===============
4.50000007032
4.50000007032
nan
nan
nan
0.0776460875399
===============
4.50000007032
4.50000007032
nan
nan
nan
0.0776460875399
===============
4.50000007032
4.50000007032
nan
nan
nan
0.0776460875399
===============
4.50000007032
4.50000007032
nan
nan
nan
0.0776460875399
===============
4.50000007032
4.50000007032
nan
nan
nan
0.0776460875399
===============
4.50000007032
4.50000007032
nan
nan
nan
0.0776460875399
===============
4.50000007032
4.50000007032
nan
nan
nan
0.0776460875399
===============
4.50000007032
4.50000007032
nan
nan
nan
0.0776460875399
===============
4.50000007032
4.50000007032
nan
nan
nan
0.0776460875399
===============
4.50000007032
4.50000007032
nan
nan
nan
0.0776460875399
Traceback (most recent call last):

  File "<ipython-input-1-4ead74e3e67e>", line 1, in <module>
    runfile('/Users/nicgaspar/LandlabDiffusionFluvialExamples/diffusion_fluvial_test_one_outlet.py', wdir='/Users/nicgaspar/LandlabDiffusionFluvialExamples')

  File "/Users/nicgaspar/anaconda/lib/python2.7/site-packages/spyder/utils/site/sitecustomize.py", line 866, in runfile
    execfile(filename, namespace)

  File "/Users/nicgaspar/anaconda/lib/python2.7/site-packages/spyder/utils/site/sitecustomize.py", line 94, in execfile
    builtins.execfile(filename, *where)

  File "/Users/nicgaspar/LandlabDiffusionFluvialExamples/diffusion_fluvial_test_one_outlet.py", line 52, in <module>
    sp.run_one_step(dt)

  File "/Users/nicgaspar/landlab/landlab/components/stream_power/fastscape_stream_power.py", line 442, in run_one_step
    rainfall_intensity_if_used=rainfall_intensity_if_used)

  File "/Users/nicgaspar/landlab/landlab/components/stream_power/fastscape_stream_power.py", line 382, in erode
    threshdt, alpha_divided, n, z)

  File "landlab/components/stream_power/cfuncs.pyx", line 185, in landlab.components.stream_power.cfuncs.erode_with_link_alpha_fixthresh (landlab/components/stream_power/cfuncs.c:3142)
    assert niter < 50, 'failure to converge in SP solver'

AssertionError: failure to converge in SP solver

**Comment by gregtucker** [comment]
@nicgaspar line 170 in cfuncs.pyx is designed to prevent this:
        if src_id != dst_id and z[src_id] > z[dst_id]:
Yet the output above suggests that the solver loop is getting invoked with z[src_id] == z[dst_id]

Can you check your cfuncs.pyx and confirm that the line above exists?

**Comment by nicgaspar** [comment]
thanks @gtucker. Yes, I've got that line in my cfuncs.pyx. We will keep looking. Thanks for checking for us.
