### ISSUE TITLE
New Errors when updating Landlab in Green Ampt Infiltration

### ISSUE THREAD

**Issue by alangston** [landlab/landlab#530]
I just updated landlab and when I run tests, I've gotten a new set of errors. 

I'm with @kbarnhart and she recommends that I tag @jadams15 since she was the last person to edit these files. 

```python
FAIL: Doctest: landlab.components.soil_moisture.infiltrate_soil_green_ampt.SoilInfiltrationGreenAmpt
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\Abby\Anaconda2\lib\doctest.py", line 2226, in runTest
    raise self.failureException(self.format_failure(new.getvalue()))
AssertionError: Failed doctest test for landlab.components.soil_moisture.infiltrate_soil_green_ampt.SoilInfiltrationGreenAmpt
  File "c:\users\abby\git\landlab\landlab\components\soil_moisture\infiltrate_soil_green_ampt.py", line 11, in SoilInfiltrationGreenAmpt

----------------------------------------------------------------------
File "c:\users\abby\git\landlab\landlab\components\soil_moisture\infiltrate_soil_green_ampt.py", line 90, in landlab.components.soil_moisture.infiltrate_soil_green_ampt.SoilInfiltrationGreenAmpt
Failed example:
    for i in range(10):  # 100s total
        SI.run_one_step(10.)
Exception raised:
    Traceback (most recent call last):
      File "C:\Users\Abby\Anaconda2\lib\doctest.py", line 1315, in __run
        compileflags, 1) in test.globs
      File "<doctest landlab.components.soil_moisture.infiltrate_soil_green_ampt.SoilInfiltrationGreenAmpt[10]>", line 2, in <module>
        SI.run_one_step(10.)
      File "c:\users\abby\git\landlab\landlab\components\soil_moisture\infiltrate_soil_green_ampt.py", line 270, in run_one_step
        self.i_act[full_infil_indx] = (self._water_depth) - self._lilwater
    ValueError: shape mismatch: value array of shape (12,) could not be broadcast to indexing result of shape (6,)
----------------------------------------------------------------------
File "c:\users\abby\git\landlab\landlab\components\soil_moisture\infiltrate_soil_green_ampt.py", line 92, in landlab.components.soil_moisture.infiltrate_soil_green_ampt.SoilInfiltrationGreenAmpt
Failed example:
    mg.at_node['surface_water__depth']
Expected:
    array([  1.00000000e-08,   1.00000000e-08,   1.00000000e-08,
             1.00000000e-08,   1.00000000e-08,   1.00000000e-08,
             9.88530416e-03,   9.88530416e-03,   9.88530416e-03,
             9.88530416e-03,   9.88530416e-03,   9.88530416e-03])
Got:
    array([ 0.01,  0.01,  0.01,  0.01,  0.01,  0.01,  0.01,  0.01,  0.01,
            0.01,  0.01,  0.01])
----------------------------------------------------------------------
File "c:\users\abby\git\landlab\landlab\components\soil_moisture\infiltrate_soil_green_ampt.py", line 97, in landlab.components.soil_moisture.infiltrate_soil_green_ampt.SoilInfiltrationGreenAmpt
Failed example:
    mg.at_node['soil_water_infiltration__depth']
Expected:
    array([ 0.20999999,  0.20999999,  0.20999999,  0.20999999,  0.20999999,
           0.20999999,  0.2001147 ,  0.2001147 ,  0.2001147 ,  0.2001147 ,
           0.2001147 ,  0.2001147 ])
Got:
    array([ 0.2,  0.2,  0.2,  0.2,  0.2,  0.2,  0.2,  0.2,  0.2,  0.2,  0.2,
            0.2])

>>  raise self.failureException(self.format_failure(<StringIO.StringIO instance at 0x0000000011B08B48>.getvalue()))
```

**Comment by nicgaspar** [comment]
@alangston Thanks for posting this. It's slightly strange because I just updated Landlab too, and I don't get any errors. Are you running the developer version or a binary? It might be helpful to know your set-up (OS, python version, etc.) At least one of those errors seems like it might be a rounding thing, which maybe is related to the version of Python that you are running. 

@jadams15 Is defending in a week and pretty busy, so she probably won't be able to get to this error soon. I will definitely try and help though. Thanks for understanding.

**Comment by kbarnhart** [comment]
thanks @nicgaspar. Good luck @jadams15!!!

I have a few ideas to debug this and will post updates as we work through them.

**Comment by kbarnhart** [comment]
@mcflugen these tests fixed the error on @alangston computer. I'll close this.
