### ISSUE TITLE
landlab cannot read geotiff files

### ISSUE THREAD

**Issue by nicgaspar** [landlab/landlab#542]
Bodo Bookhagen emailed me the attached code. Here is text from his email:

"I attach a short geotiff_reader based on gdal that import geotiff files into landlab as mg. I think that most GIS users will have geotiff files and including a reader would allow to reduce file sizes."

This code requires the gdal library. I'm not sure what the Landlab team thinks about that dependency.
[load_dem_tif.txt](https://github.com/landlab/landlab/files/1304068/load_dem_tif.txt)

**Comment by gregtucker** [comment]
Interesting idea. Before we go the full step of adding gdal as another dependency, do we currently have a function(s) to convert a 2D numpy array into a RasterModelGrid? If so, then it should be easy to go geotiff => numpy array, then numpy array => Landlab grid ... probably just a few lines of code, which we could put in a demo "how to" notebook.

**Comment by nicgaspar** [comment]
Seems like we (even I) could write that function, if that is all that is needed.

**Comment by kbarnhart** [comment]
A tangentially related thought: 

At the moment writing out to esrii ascii doesn't write a value for the lower left corner or the projection (project 4 string, perhaps). 

I know some users have found this irritating. Mostly because they expect that after reading in a georeference esrii ascii to landlab, using it for modeling, and then writing out an esrii ascii they will be able to see the two fields in a GIS on top of one another. 

Perhaps as we address this issue, we can fold in a way to store the necessary info on the grid for writing out georeferenced fields.

**Comment by nicgaspar** [comment]
That issue with the lower left corner being missing in write esrii ascii sounds like a bug? We should definitely fix that. But the projection issue is an ongoing discussion that we have never resolved. I'd be happy to revive it though.

**Comment by bpurinton** [comment]
Hi all,

My name is Ben Purinton and I'm actually one of Bodo's grad students. I've been playing around a lot with landlab over the past few weeks and trying also to use GeoTiffs (via gdal) using the little reader that Bodo wrote (I agree with him, GeoTiff compatibility is important and I use gdal in about every script I write). Mostly I'm just working with the flow-router (trying to get away from matlab/GIS for these calculations). I'm having an issue now using GeoTiffs though. When I convert to ASCII and use the built in `landlab.io.esri_ascii.read_esri_ascii` function my scripts work fine and I can even write grids (such as drainage area) back out to GeoTiff with:

`numpy_array = np.flipud(mg.at_node['drainage_area'].reshape(nr_of_y_cells, nr_of_x_cells))`

However, when I try and do the same with a the original GeoTiff (using Bodo's GeoTiff reader linked above), I get an error right off using `landlab.components.FlowRouter`:

`Traceback (most recent call last):

  File "<ipython-input-6-14d3f8a17152>", line 2, in <module>
    fr.run_one_step()

  File "C:\ProgramData\Miniconda2\lib\site-packages\landlab\components\flow_routing\route_flow_dn.py", line 370, in run_one_step
    self.accumulate_flow()

  File "C:\ProgramData\Miniconda2\lib\site-packages\landlab\components\flow_accum\flow_accumulator.py", line 900, in accumulate_flow
    self.flow_director.run_one_step()

  File "C:\ProgramData\Miniconda2\lib\site-packages\landlab\components\flow_director\flow_director_d8.py", line 149, in run_one_step
    self.direct_flow()

  File "C:\ProgramData\Miniconda2\lib\site-packages\landlab\components\flow_director\flow_director_d8.py", line 190, in direct_flow
    baselevel_nodes=baselevel_nodes)

  File "C:\ProgramData\Miniconda2\lib\site-packages\landlab\components\flow_director\flow_direction_DN.py", line 210, in flow_directions
    steepest_slope)

  File "landlab\components\flow_director\cfuncs.pyx", line 15, in landlab.components.flow_director.cfuncs.adjust_flow_receivers (landlab/components/flow_director\cfuncs.c:1708)

ValueError: Buffer dtype mismatch, expected 'DTYPE_INT_t' but got 'long long'`

Do you know what the problem is? I've tried converting the data to integer format before running the code, but that didn't help. The strange thing is Bodo did not have this issue.

Thanks!!
Ben
