### ISSUE TITLE
Test failure installing developer version on AWS

### ISSUE THREAD

**Issue by ChristinaB** [landlab/landlab#630]
Here is what I got for my report: 

landlab version v1.2.0+500.g5329895
landlab is installed in /home/ubuntu/landlab/landlab
Python version 3.6.4 |Anaconda custom (64-bit)| (default, Jan 16 2018, 18:10:19) [GCC 7.2.0]
nose version 1.3.7
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ubuntu/landlab/landlab/testing/nosetester.py", line 79, in test
    return super(LandlabTester, self).test(**kwds)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/numpy/testing/nose_tools/nosetester.py", line 406, in test
    label, verbose, extra_argv, doctests, coverage, timer)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/numpy/testing/nose_tools/nosetester.py", line 300, in prepare_test_args
    if self.check_fpu_mode:
AttributeError: 'LandlabTester' object has no attribute 'check_fpu_mode'

**Comment by ChristinaB** [comment]
I also got an error using this code:

**Comment by margauxmouchene** [comment]
For the AttributeError: do you know what version of numpy is installed? This error looks like #616 and might be due to numpy 1.14. Landlab should work anyway, even if the test fails.
