### ISSUE TITLE
FAIL: Doctest: landlab.core.utils.strip_grid_from_method_docstring

### ISSUE THREAD

**Issue by kbarnhart** [landlab/landlab#702]
For a while I was getting four persistent errors on Landlab Master. I got rid of three of them with PRs #697 and #698.  Currently on my machine and (at least) Travis, the following error persists. 

using magical git blame, it appears that this was originally written by @SiccarPoint. If you think I should assign someone else, let me know. 

```
======================================================================
FAIL: Doctest: landlab.core.utils.strip_grid_from_method_docstring
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/anaconda3/lib/python3.6/doctest.py", line 2199, in runTest
    raise self.failureException(self.format_failure(new.getvalue()))
AssertionError: Failed doctest test for landlab.core.utils.strip_grid_from_method_docstring
  File "/Users/barnhark/projects/landlab/guissepe/landlab/landlab/core/utils.py", line 317, in strip_grid_from_method_docstring

----------------------------------------------------------------------
File "/Users/barnhark/projects/landlab/guissepe/landlab/landlab/core/utils.py", line 352, in landlab.core.utils.strip_grid_from_method_docstring
Failed example:
    help(dummy_func)
Expected:
    Help on function dummy_func_to_demonstrate_docstring_modification in module landlab.grid.mappers:
    <BLANKLINE>
    dummy_func_to_demonstrate_docstring_modification(grid, some_arg)
        A dummy function to demonstrate automated docstring changes.
    <BLANKLINE>
        Construction::
    <BLANKLINE>
            grid.dummy_func_to_demonstrate_docstring_modification(some_arg)
    <BLANKLINE>
        Parameters
        ----------
        some_arg : whatever
            A dummy argument.
    <BLANKLINE>
        Examples
        --------
        ...
    <BLANKLINE>
Got:
    Help on function dummy_func_to_demonstrate_docstring_modification in module landlab.grid.mappers:
    <BLANKLINE>
    dummy_func_to_demonstrate_docstring_modification(grid, some_arg)
        A dummy function to demonstrate automated docstring changes.
    <BLANKLINE>
        Parameters
        ----------
        some_arg : whatever
            A dummy argument.
    <BLANKLINE>
        Examples
        --------
        ...
    <BLANKLINE>
        LLCATS: DEPR MAP
    <BLANKLINE>

>>  raise self.failureException(self.format_failure(<_io.StringIO object at 0x1020c7828>.getvalue()))
```

**Comment by mcflugen** [comment]
@kbarnhart @SiccarPoint It seems that the doctest for `strip_grid_from_method_docstring` wasn't updated with an update in `dummy_func_to_demonstrate_docstring_modification`. Somewhere along the way we,
1. Removed the `Construction` section from all our docstrings
2. Added the `LLCATS` tag to docstrings

I think it's safe to just update the expected strings for the failing doctests to match what we're now getting.

**Comment by SiccarPoint** [comment]
Nothing wrong with the function - looks like someone caught up my dummy func in a drive to clean up docs and broke the test that way. Easy fix.

**Comment by SiccarPoint** [comment]
See PR #706
