### ISSUE TITLE
testing, again

### ISSUE THREAD

**Issue by SiccarPoint** [landlab/landlab#704]
Following on from #700, I tried deprecating numpy to 1.13 on my Python 3 environment. Now I'm getting a new and exciting error...

```
Failed to import the site module
Traceback (most recent call last):
  File "/Users/danhobley/anaconda/envs/mypython3/lib/python3.6/site.py", line 541, in <module>
    main()
  File "/Users/danhobley/anaconda/envs/mypython3/lib/python3.6/site.py", line 522, in main
    known_paths = addusersitepackages(known_paths)
  File "/Users/danhobley/anaconda/envs/mypython3/lib/python3.6/site.py", line 282, in addusersitepackages
    user_site = getusersitepackages()
  File "/Users/danhobley/anaconda/envs/mypython3/lib/python3.6/site.py", line 258, in getusersitepackages
    user_base = getuserbase() # this will also set USER_BASE
  File "/Users/danhobley/anaconda/envs/mypython3/lib/python3.6/site.py", line 248, in getuserbase
    USER_BASE = get_config_var('userbase')
  File "/Users/danhobley/anaconda/envs/mypython3/lib/python3.6/sysconfig.py", line 608, in get_config_var
    return get_config_vars().get(name)
  File "/Users/danhobley/anaconda/envs/mypython3/lib/python3.6/sysconfig.py", line 587, in get_config_vars
    import _osx_support
  File "/Users/danhobley/anaconda/envs/mypython3/lib/python3.6/_osx_support.py", line 4, in <module>
    import re
  File "/Users/danhobley/anaconda/envs/mypython3/lib/python3.6/re.py", line 122, in <module>
    import enum
  File "/Users/danhobley/anaconda/envs/mypython3/lib/python3.6/enum.py", line 2, in <module>
    from types import MappingProxyType, DynamicClassAttribute
  File "/Users/danhobley/anaconda/envs/mypython3/lib/python3.6/types.py", line 171, in <module>
    import functools as _functools
  File "/Users/danhobley/anaconda/envs/mypython3/lib/python3.6/functools.py", line 21, in <module>
    from collections import namedtuple
  File "/Users/danhobley/anaconda/envs/mypython3/lib/python3.6/collections/__init__.py", line 32, in <module>
    from reprlib import recursive_repr as _recursive_repr
  File "/Applications/QGIS.app/Contents/Resources/python/reprlib/__init__.py", line 7, in <module>
    raise ImportError('This package should not be accessible on Python 3. '
ImportError: This package should not be accessible on Python 3. Either you are trying to run from the python-future src folder or your installation of python-future is corrupted.
```

I don't appear to have a conda package python-future at all, and it doesn't seem to even exist. My Py3 distribution is up to date, excepting numpy (and necessarily a concurrent change to `numba`). Ideas?

**Comment by SiccarPoint** [comment]
Ah, wait. My whole Python 3 distribution is screwed up - can't launch ipython either. Will try to deal with this independently. Closing.
