### ISSUE TITLE
Critical Landlab install issues

### ISSUE THREAD

**Issue by SiccarPoint** [landlab/landlab#705]
I have attempted to downgrade my Python 2 numpy version to 1.13 to enable testing.
```
>>> conda install numpy=1.13
>>> python setup.py develop
```
I can launch Python just fine. However, my Landlab install now appears very broken. An attempt to test, or to even `import landlab`, kicks off:
```
Unable to import landlab. You may not have landlab installed.
Here is your sys.path
/Library/Frameworks/GDAL.framework/Headers
/Library/Frameworks/GDAL.framework/Programs
/Applications/QGIS.app/Contents/Resources/python
/Users/danhobley/anaconda/lib/python27.zip
/Users/danhobley/anaconda/lib/python2.7
/Users/danhobley/anaconda/lib/python2.7/plat-darwin
/Users/danhobley/anaconda/lib/python2.7/plat-mac
/Users/danhobley/anaconda/lib/python2.7/plat-mac/lib-scriptpackages
/Users/danhobley/anaconda/lib/python2.7/lib-tk
/Users/danhobley/anaconda/lib/python2.7/lib-old
/Users/danhobley/anaconda/lib/python2.7/lib-dynload
/Users/danhobley/anaconda/lib/python2.7/site-packages
/Users/danhobley/anaconda/lib/python2.7/site-packages/aeosa
/Users/danhobley/git_landlab
/Users/danhobley/grain_hills
/Users/danhobley/anaconda/lib/python2.7/site-packages
Traceback (most recent call last):
  File "test-installed-landlab.py", line 25, in <module>
    import landlab
  File "/Users/danhobley/git_landlab/landlab/__init__.py", line 37, in <module>
    from .field.scalar_data_fields import FieldError
  File "/Users/danhobley/git_landlab/landlab/field/__init__.py", line 4, in <module>
    from .graph_field import GraphFields
  File "/Users/danhobley/git_landlab/landlab/field/graph_field.py", line 2, in <module>
    import xarray as xr
  File "/Users/danhobley/anaconda/lib/python2.7/site-packages/xarray/__init__.py", line 6, in <module>
    from .core.alignment import align, broadcast, broadcast_arrays
  File "/Users/danhobley/anaconda/lib/python2.7/site-packages/xarray/core/alignment.py", line 10, in <module>
    from . import utils
  File "/Users/danhobley/anaconda/lib/python2.7/site-packages/xarray/core/utils.py", line 13, in <module>
    import pandas as pd
  File "/Users/danhobley/anaconda/lib/python2.7/site-packages/pandas/__init__.py", line 23, in <module>
    from pandas.compat.numpy import *
  File "/Users/danhobley/anaconda/lib/python2.7/site-packages/pandas/compat/__init__.py", line 421, in <module>
    raise ImportError('dateutil 2.5.0 is the minimum required version')
ImportError: dateutil 2.5.0 is the minimum required version
```

I should note I previously tried to use the `requirements.txt` file to see if it would downgrade Python automatically (it doesn't), so this could be related to that issue.

**Comment by SiccarPoint** [comment]
(Assigning @mcflugen as person most likely to recognise this issue?)

**Comment by SiccarPoint** [comment]
After further poking around, I suspect that somehow I have a versioning conflict, possibly related to QGIS. Everything is fine if run off a newly created VM. Considering a full purge-and-reinstall of conda. Less drastic ideas welcome before I get that far.

**Comment by SiccarPoint** [comment]
OK, as suspected, this is a QGIS thing. Removing references to QGIS from my PATH and PYTHONPATH did the job. QGIS still seems functional. Funny that it only started yesterday. There you go.
