### ISSUE TITLE
Failing tests, redux

### ISSUE THREAD

**Issue by SiccarPoint** [landlab/landlab#710]
Can someone give me an update on what tests are currently failing in `master`? I have 8 fails right now, all along the lines of comparing a `MaskedIterator` to an array. This is Python 2. An example:
```
x: array(<numpy.ma.core.MaskedIterator object at 0x107a49990>, dtype=object)
y: array([0, 1])
```
Is this a known fail, or has my rebuild of `conda` screwed me up locally? I clearly can't yet check on appveyor...

**Comment by kbarnhart** [comment]
@SiccarPoint known fail. 

These cropped up right after the last of those 4 persistent errors I worked (and assigned to you) to squash.

I don't get the locally right now, but I see them on Travis and AppVeyor. 

8 is the right number.

**Comment by SiccarPoint** [comment]
Sweet. Thank you!

**Comment by kbarnhart** [comment]
I wanted to follow up with persistent errors. 

Beyond the 8 masked array errors, is anyone else seeing the following error on `master`:

```
======================================================================
ERROR: Failure: ValueError ('/Users/barnhark/projects/landlab/landlab/landlab/grid/tests/testing_hex_grid/__init__.py/__init__.pyc' is not a package)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/anaconda3/lib/python3.6/site-packages/nose/failure.py", line 39, in runTest
    raise self.exc_val.with_traceback(self.tb)
  File "/anaconda3/lib/python3.6/site-packages/nose/loader.py", line 417, in loadTestsFromName
    addr.filename, addr.module)
  File "/anaconda3/lib/python3.6/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/anaconda3/lib/python3.6/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/anaconda3/lib/python3.6/imp.py", line 244, in load_module
    return load_package(name, filename)
  File "/anaconda3/lib/python3.6/imp.py", line 210, in load_package
    raise ValueError('{!r} is not a package'.format(path))
ValueError: '/Users/barnhark/projects/landlab/landlab/landlab/grid/tests/testing_hex_grid/__init__.py/__init__.pyc' is not a package
```

**Comment by kbarnhart** [comment]
I'm closing this issue and making a new one specific to this hex grid error
