### ISSUE TITLE
test-installed-landlab script produces AttributeError

### ISSUE THREAD

**Issue by gregtucker** [landlab/landlab#721]
On branch master, up to date as of 6/5/18:

cu-biot-7-10:scripts gtucker$ python test-installed-landlab.py 
landlab version 1.1.0+705.g9d509dc
landlab is installed in /Users/gtucker/Dev/Landlab/landlab/landlab
Python version 2.7.14 | packaged by conda-forge | (default, Mar 30 2018, 18:21:11) [GCC 4.2.1 Compatible Apple LLVM 6.1.0 (clang-602.0.53)]
nose version 1.3.7
Traceback (most recent call last):
  File "test-installed-landlab.py", line 35, in <module>
    extra_argv=args, raise_warnings='release')
  File "/Users/gtucker/Dev/Landlab/landlab/landlab/testing/nosetester.py", line 79, in test
    return super(LandlabTester, self).test(**kwds)
  File "/anaconda/lib/python2.7/site-packages/numpy/testing/nose_tools/nosetester.py", line 406, in test
    label, verbose, extra_argv, doctests, coverage, timer)
  File "/anaconda/lib/python2.7/site-packages/numpy/testing/nose_tools/nosetester.py", line 300, in prepare_test_args
    if self.check_fpu_mode:
AttributeError: 'LandlabTester' object has no attribute 'check_fpu_mode'

**Comment by kbarnhart** [comment]
This is a duplicate of #616 (and subsequent similar issues tagged at the bottom of #616)

Its a numpy version issue

**Comment by gregtucker** [comment]
Ok, closing this
