### ISSUE TITLE
Trouble with SinkFiller

### ISSUE THREAD

**Issue by rbunel** [landlab/landlab#781]
Hello !

I'm trying to fill pits with slope in a dem :
[dem_landlab.txt](https://github.com/landlab/landlab/files/2340834/dem_landlab.txt)

I've executed the code :

`watershed_dem = r"dem_Landlab.txt"`
`rmg, z = read_esri_ascii(watershed_dem, name='topographic__elevation')`
`sf = SinkFiller(rmg, routing='D4', apply_slope=True)`
`sf.fill_pits()` 

The function runs for a very long time (several tens of minutes) and I get the following error :

`TrueTraceback (most recent call last):`
  `Python Shell, prompt 4, line 6`
  `File "C:\Users\xxxxx\AppData\Local\Continuum\anaconda2\Lib\site-packages\landlab\components\sink_fill\fill_sinks.py", line 204, in fill_pits`
    `self.run_one_step(**kwds)`
  `File "C:\Users\xxxxx\AppData\Local\Continuum\anaconda2\Lib\site-packages\landlab\components\sink_fill\fill_sinks.py", line 252, in run_one_step`
    `lowest_elev_perim = perim_elevs[perim_elevs != out_elev].min()`
  `File "C:\Users\xxxxx\AppData\Local\Continuum\anaconda2\Lib\site-packages\numpy\core\_methods.py", line 29, in _amin`
    `return umr_minimum(a, axis, None, out, keepdims)`
`ValueError zero-size array to reduction operation minimum which has no identity`

There is no problem when the function runs without applying a slope (apply_slope=False). 
However, the calculation time remains very long (more than 15 minutes).

Do you have any idea what the problem is?

Thanks in advance for your help.

**Comment by kbarnhart** [comment]
@rbunel thanks for making an issue and for providing a minimal example. I've assigned @SiccarPoint to this as he is the primary author of the component.

**Comment by SiccarPoint** [comment]
Hi @rbunel. I suspect this might have something to do with the boundary conditions on your grid. Are you sure there's an outlet node in the grid setup? I'm not sure your current minimal example would permit one. There needs to be a FIXED_VALUE or FIXED_GRADIENT node in there somewhere.

**Comment by rbunel** [comment]
Thank you for your answer.
I interleaved in my script - just before SinkFiller - this line:

`rmg.set_watershed_boundary_condition(z,nodata_value=-9999.)`

As you had anticipated, the application of this function results in an error. Here it is:

`Traceback (most recent call last):
  Python Shell, prompt 11, line 1
  File "C:\Users\bunelrap\AppData\Local\Continuum\anaconda2\Lib\site-packages\landlab\grid\raster.py", line 5155, in set_watershed_boundary_condition
    if self.has_boundary_neighbor(min_locs[i]):
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
`

So, to define a FIXED_VALUE node somewhere, I applied the function:
`rmg.set_fixed_value_boundaries_at_grid_edges(True, True, True, True)`

I get this time this error:

`Traceback (most recent call last):
  Python Shell, prompt 10, line 3
  File "C:\Users\bunelrap\AppData\Local\Continuum\anaconda2\Lib\site-packages\landlab\components\sink_fill\fill_sinks.py", line 204, in fill_pits
    self.run_one_step(**kwds)
  File "C:\Users\bunelrap\AppData\Local\Continuum\anaconda2\Lib\site-packages\landlab\components\sink_fill\fill_sinks.py", line 239, in run_one_step
    reroute_flow=True)
  File "C:\Users\bunelrap\AppData\Local\Continuum\anaconda2\Lib\site-packages\landlab\components\flow_routing\lake_mapper.py", line 668, in map_depressions
    self._identify_depressions_and_outlets()
  File "C:\Users\bunelrap\AppData\Local\Continuum\anaconda2\Lib\site-packages\landlab\components\flow_routing\lake_mapper.py", line 579, in _identify_depressions_and_outlets
    self.find_depression_from_pit(pit_node)
  File "C:\Users\bunelrap\AppData\Local\Continuum\anaconda2\Lib\site-packages\landlab\components\flow_routing\lake_mapper.py", line 546, in find_depression_from_pit
    self.find_lowest_node_on_lake_perimeter(nodes_this_depression)
  File "C:\Users\bunelrap\AppData\Local\Continuum\anaconda2\Lib\site-packages\landlab\components\flow_routing\lake_mapper.py", line 407, in find_lowest_node_on_lake_perimeter
    'failed to find lowest perim node'
AssertionError: failed to find lowest perim node`

Can anything else be attempted?

**Comment by SiccarPoint** [comment]
This probably means you have a "floating" DEM, where the data nodes don't actually ever touch the edge of your DEM. The easiest way to deal with this will be to do this by hand.

1. Check that the call to `rmg.set_watershed_boundary_condition(z,nodata_value=-9999.)` actually did what you think despite that error. Try `imshow_grid_at_node(rmg, rmg.status_at_node)` to check everything is 4 (CLOSED_BOUNDARY) where it should be.
2. Find the lowest node in the nodes with value. Something like
```
open_nodes = np.where(rmg.status_at_node != CLOSED_BOUNDARY)[0]
min_open = z[open_nodes].argmin()
min_node_ID = open_nodes[min_open]
```
3. Set the BC by hand
```
rmg.status_at_node[min_node_ID] = FIXED_VALUE_BOUNDARY
```
Then check this looks right again by plotting.

You can import both these BOUNDARY values from landlab. That should do it.

**Comment by rbunel** [comment]
Thanks for your help.

The `AssertionError:  failed to find lowest perim node error` error persists.

   1.`rmg.set_watershed_boundary_condition(z,nodata_value=-9999.)` does not produce a row of 4 on the periphery of the watershed as it should be. Confer first image. However, the command `max(rmg.status_at_node)` shows that 4s exist somewhere even if they are not represented.

```ruby
from landlab.io import read_esri_ascii 
from landlab import CLOSED_BOUNDARY, FIXED_VALUE_BOUNDARY
from landlab import imshow_grid_at_node
from landlab.components import SinkFiller
import numpy as np

watershed_dem ="C:/Users/bunelrap/downloads/dem_landlab.txt"
rmg, z = read_esri_ascii(watershed_dem, name='topographic__elevation')

rmg.set_watershed_boundary_condition(z,nodata_value=-9999.)
Traceback (most recent call last):

  File "<ipython-input-12-141042d8832f>", line 10, in <module>
    rmg.set_watershed_boundary_condition(z,nodata_value=-9999.)

  File "C:\Users\bunelrap\AppData\Local\Continuum\anaconda2\lib\site-packages\landlab\grid\raster.py", line 5155, in set_watershed_boundary_condition
    if self.has_boundary_neighbor(min_locs[i]):

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

imshow_grid_at_node(rmg, rmg.status_at_node)
```

![image1](https://user-images.githubusercontent.com/42864541/45214976-347c3e00-b29c-11e8-9b96-9d4152ad157f.png)

   2. I tried to define a limit by hand according to your instructions but the `AssertionError:  failed to find lowest perim node error` error persists.

```ruby
open_nodes = np.where(rmg.status_at_node != CLOSED_BOUNDARY)[0]
min_open = z[open_nodes].argmin()
min_node_ID = open_nodes[min_open]

rmg.status_at_node[min_node_ID] = FIXED_VALUE_BOUNDARY

imshow_grid_at_node(rmg, rmg.status_at_node)
```

![image2](https://user-images.githubusercontent.com/42864541/45214990-41992d00-b29c-11e8-8c97-cfe20ef084ef.png)

```ruby
sf = SinkFiller(rmg, routing='D4', apply_slope=True)
sf.fill_pits()
Traceback (most recent call last):

  File "<ipython-input-15-35d252670b74>", line 2, in <module>
    sf.fill_pits()

  File "C:\Users\bunelrap\AppData\Local\Continuum\anaconda2\lib\site-packages\landlab\components\sink_fill\fill_sinks.py", line 204, in fill_pits
    self.run_one_step(**kwds)

  File "C:\Users\bunelrap\AppData\Local\Continuum\anaconda2\lib\site-packages\landlab\components\sink_fill\fill_sinks.py", line 239, in run_one_step
    reroute_flow=True)

  File "C:\Users\bunelrap\AppData\Local\Continuum\anaconda2\lib\site-packages\landlab\components\flow_routing\lake_mapper.py", line 668, in map_depressions
    self._identify_depressions_and_outlets()

  File "C:\Users\bunelrap\AppData\Local\Continuum\anaconda2\lib\site-packages\landlab\components\flow_routing\lake_mapper.py", line 579, in _identify_depressions_and_outlets
    self.find_depression_from_pit(pit_node)

  File "C:\Users\bunelrap\AppData\Local\Continuum\anaconda2\lib\site-packages\landlab\components\flow_routing\lake_mapper.py", line 546, in find_depression_from_pit
    self.find_lowest_node_on_lake_perimeter(nodes_this_depression)

  File "C:\Users\bunelrap\AppData\Local\Continuum\anaconda2\lib\site-packages\landlab\components\flow_routing\lake_mapper.py", line 407, in find_lowest_node_on_lake_perimeter
    'failed to find lowest perim node'

AssertionError: failed to find lowest perim node

```

**Comment by SiccarPoint** [comment]
Hmmm. This doesn't make sense to me. I'm guessing the problem must be in the DEM reader, which is @nicgaspar and @jadams15. I note Katy has spotted you're running very old Landlab in another thread. Try updating as well and see if this problem goes away.

**Comment by kbarnhart** [comment]
@rbune based on the output of the command

```python
rmg.set_watershed_boundary_condition(z,nodata_value=-9999.)
```
l suspect that your DEM has two nodes that have the same elevation and are on the boundary. 

I also suspect based on the error message that you are seeing here, that you are using an old version of landlab. I say this because I revised the error message in this particular case so that it is more useful. 

@saisiddu this looks a lot like Issue #651 which I think occurred because there was a sink on the boundary of the watershed. What do you think?

**Comment by rbunel** [comment]
So I was able to get the most recent version of landlab (1.5.2.).  I kept only one minimum in my dem to facilitate outlet identification by the set_watershed_boundary_conditions function.

But `SinkFiller` produces the following error:

```python
Traceback (most recent call last):

  File "<ipython-input-47-35d252670b74>", line 2, in <module>
    sf.fill_pits()

  File "C:\Users\bunelrap\AppData\Local\Continuum\anaconda2\lib\site-packages\landlab\components\sink_fill\fill_sinks.py", line 201, in fill_pits
    self.run_one_step(**kwds)

  File "C:\Users\bunelrap\AppData\Local\Continuum\anaconda2\lib\site-packages\landlab\components\sink_fill\fill_sinks.py", line 249, in run_one_step
    lowest_elev_perim = perim_elevs[perim_elevs != out_elev].min()

  File "C:\Users\bunelrap\AppData\Local\Continuum\anaconda2\lib\site-packages\numpy\core\_methods.py", line 29, in _amin
    return umr_minimum(a, axis, None, out, keepdims)

ValueError: zero-size array to reduction operation minimum which has no identity
```

**Comment by SiccarPoint** [comment]
I still think this is a boundary condition issue. Try resolving #784 first, as this may sort itself out once you have the flow directions working correctly.

**Comment by rbunel** [comment]
SinkFiller always produces the following error when I try to apply a slope to flat areas (apply_slope = True), although I think I have correctly specified the boundary conditions #784 .
```python
Traceback (most recent call last):

  File "<ipython-input-121-055d21856cfa>", line 26, in <module>
    sf.fill_pits()

  File "C:\Users\bunelrap\AppData\Local\Continuum\anaconda2\lib\site-packages\landlab\components\sink_fill\fill_sinks.py", line 201, in fill_pits
    self.run_one_step(**kwds)

  File "C:\Users\bunelrap\AppData\Local\Continuum\anaconda2\lib\site-packages\landlab\components\sink_fill\fill_sinks.py", line 249, in run_one_step
    lowest_elev_perim = perim_elevs[perim_elevs != out_elev].min()

  File "C:\Users\bunelrap\AppData\Local\Continuum\anaconda2\lib\site-packages\numpy\core\_methods.py", line 29, in _amin
    return umr_minimum(a, axis, None, out, keepdims)

ValueError: zero-size array to reduction operation minimum which has no identity

```

I'll come back to you if I can find a solution. Thanks a lot @SiccarPoint for all your help already provided.
