### ISSUE TITLE
FlowAccumulator MFD on flat surfaces

### ISSUE THREAD

**Issue by SiccarPoint** [landlab/landlab#802]
This isn't exactly urgent, but wanted to flag it while it's in front of me.

The FlowAccumulator (and so, presumably, the FlowDirectors as well) Error confusingly if called on a flat surface. The error message is opaque, and it's an IndexError. IMO calling on a flat surface is a potential use case, albeit rare.

```
    mg = RasterModelGrid((5, 5), 1.)
    z = mg.add_zeros('node', 'topographic__elevation')
    fa = FlowAccumulator(mg, flow_director='MFD')
    fa.run_one_step()
Traceback (most recent call last):
  File "/Users/danhobley/git_landlab/landlab/components/stream_power/tests/test_TL.py", line 17, in test_multidirection
    fa.run_one_step()
  File "/Users/danhobley/git_landlab/landlab/components/flow_accum/flow_accumulator.py", line 1034, in run_one_step
    self.accumulate_flow()
  File "/Users/danhobley/git_landlab/landlab/components/flow_accum/flow_accumulator.py", line 988, in accumulate_flow
    s = flow_accum_to_n.make_ordered_node_array_to_n(r, p)
  File "/Users/danhobley/git_landlab/landlab/components/flow_accum/flow_accum_to_n.py", line 458, in make_ordered_node_array_to_n
    construct_it(baselevel_nodes)  # don't think this is a bottleneck, so no C++
  File "/Users/danhobley/git_landlab/landlab/components/flow_accum/flow_accum_to_n.py", line 169, in construct__stack
    visited_enough = num_visits[visited] == self.num_receivers[visited]
IndexError: arrays used as indices must be of integer (or boolean) type
```

In this case, the Error is resolved by roughening the surface.

**Comment by kbarnhart** [comment]
Thanks for pointing this out @SiccarPoint 

Here is a MCE:

```python
from landlab import RasterModelGrid
from landlab.components import (FlowAccumulator)


for fd in ['FlowDirectorSteepest', 
           'FlowDirectorD8', 
           'FlowDirectorDINF', 
           'FlowDirectorMFD']:
    mg = RasterModelGrid(40, 60, dx=10)
    z = mg.add_zeros('topographic__elevation', at='node')
    fa = FlowAccumulator(mg, flow_director=fd)
    try:
        fa.run_one_step()
        print(fd + ' success')
    except IndexError:
        print(fd + ' failed')
    del mg, z, fa
FlowDirectorSteepest success
FlowDirectorD8 success
FlowDirectorDINF failed
FlowDirectorMFD failed
```

I've seen this error before when a -1 (our `BAD_INDEX_VALUE`) is used as an index in the cythonized part of the code. Thats not why its happening here though. 

I have a few ideas of what the issue is, but am not sure yet. Will work on it (but probably slowly).
