### ISSUE TITLE
Errors after merging NetworkModelGrid branch

### ISSUE THREAD

**Issue by kbarnhart** [landlab/landlab#855]
Merging #848 created an unexpected error:

```
=================================== FAILURES ===================================
_________ [doctest] landlab.io.shapefile.read_shapefile.read_shapefile _________
042     --------
043     First, we make a simple shapefile
044 
045     >>> try:
046     ...     from StringIO import StringIO
047     ... except ImportError:
048     ...     from io import BytesIO as StringIO
049 
050     >>> import shapefile
051     >>> w = shapefile.Writer()
UNEXPECTED EXCEPTION: Exception('Either the target filepath, or any of shp, shx, or dbf must be set to create a shapefile.',)
Traceback (most recent call last):
  File "/home/travis/miniconda/envs/_testing/lib/python2.7/doctest.py", line 1315, in __run
    compileflags, 1) in test.globs
  File "<doctest landlab.io.shapefile.read_shapefile.read_shapefile[2]>", line 1, in <module>
  File "/home/travis/miniconda/envs/_testing/lib/python2.7/site-packages/shapefile.py", line 1029, in __init__
    raise Exception('Either the target filepath, or any of shp, shx, or dbf must be set to create a shapefile.')
Exception: Either the target filepath, or any of shp, shx, or dbf must be set to create a shapefile.
/home/travis/build/landlab/landlab/landlab/io/shapefile/read_shapefile.py:51: UnexpectedException
```

**Comment by kbarnhart** [comment]
I think it will be fixed by adding the extensions in setup.py
