### ISSUE TITLE
Errors installing with dependencies `pip install -e .`

### ISSUE THREAD

**Issue by pfeiffea** [landlab/landlab#974]
Hi All. When I run `pip install -e .` (as per https://github.com/landlab/landlab/wiki/Installing-Landlab-from-source-code-(%22developer-install%22) ) I get a long set of errors. See below. Not sure if this is a 'me' issue, or a landlab issue. 

```(landlab_dev) PS C:\Users\pfeif\Documents\GitHub\landlab> pip install -e .
Obtaining file:///C:/Users/pfeif/Documents/GitHub/landlab
Requirement already satisfied: bmipy<1 in c:\users\pfeif\miniconda3\envs\landlab_dev\lib\site-packages (from landlab==1.9.0+176.gd414df44d.dirty) (0.3.2)
Requirement already satisfied: matplotlib in c:\users\pfeif\miniconda3\envs\landlab_dev\lib\site-packages (from landlab==1.9.0+176.gd414df44d.dirty) (3.1.0)
Requirement already satisfied: netcdf4 in c:\users\pfeif\miniconda3\envs\landlab_dev\lib\site-packages (from landlab==1.9.0+176.gd414df44d.dirty) (1.5.1.2)
Requirement already satisfied: pyyaml in c:\users\pfeif\miniconda3\envs\landlab_dev\lib\site-packages (from landlab==1.9.0+176.gd414df44d.dirty) (5.1.1)
Requirement already satisfied: pyshp in c:\users\pfeif\miniconda3\envs\landlab_dev\lib\site-packages (from landlab==1.9.0+176.gd414df44d.dirty) (2.1.0)
Requirement already satisfied: scipy<1.3 in c:\users\pfeif\miniconda3\envs\landlab_dev\lib\site-packages (from landlab==1.9.0+176.gd414df44d.dirty) (1.2.1)
Requirement already satisfied: six in c:\users\pfeif\miniconda3\envs\landlab_dev\lib\site-packages (from landlab==1.9.0+176.gd414df44d.dirty) (1.12.0)
Requirement already satisfied: statsmodels in c:\users\pfeif\miniconda3\envs\landlab_dev\lib\site-packages (from landlab==1.9.0+176.gd414df44d.dirty) (0.9.0)
Requirement already satisfied: xarray in c:\users\pfeif\miniconda3\envs\landlab_dev\lib\site-packages (from landlab==1.9.0+176.gd414df44d.dirty) (0.12.1)
Requirement already satisfied: jinja2 in c:\users\pfeif\miniconda3\envs\landlab_dev\lib\site-packages (from bmipy<1->landlab==1.9.0+176.gd414df44d.dirty) (2.10.1)
Requirement already satisfied: numpy in c:\users\pfeif\miniconda3\envs\landlab_dev\lib\site-packages (from bmipy<1->landlab==1.9.0+176.gd414df44d.dirty) (1.16.3)
Requirement already satisfied: click in c:\users\pfeif\miniconda3\envs\landlab_dev\lib\site-packages (from bmipy<1->landlab==1.9.0+176.gd414df44d.dirty) (7.0)
Requirement already satisfied: black in c:\users\pfeif\miniconda3\envs\landlab_dev\lib\site-packages (from bmipy<1->landlab==1.9.0+176.gd414df44d.dirty) (19.3b0)
Requirement already satisfied: kiwisolver>=1.0.1 in c:\users\pfeif\miniconda3\envs\landlab_dev\lib\site-packages (from matplotlib->landlab==1.9.0+176.gd414df44d.dirty) (1.1.0)
Requirement already satisfied: python-dateutil>=2.1 in c:\users\pfeif\miniconda3\envs\landlab_dev\lib\site-packages (from matplotlib->landlab==1.9.0+176.gd414df44d.dirty) (2.8.0)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 in c:\users\pfeif\miniconda3\envs\landlab_dev\lib\site-packages (from matplotlib->landlab==1.9.0+176.gd414df44d.dirty) (2.4.0)
Requirement already satisfied: cycler>=0.10 in c:\users\pfeif\miniconda3\envs\landlab_dev\lib\site-packages (from matplotlib->landlab==1.9.0+176.gd414df44d.dirty) (0.10.0)
Requirement already satisfied: cftime in c:\users\pfeif\miniconda3\envs\landlab_dev\lib\site-packages (from netcdf4->landlab==1.9.0+176.gd414df44d.dirty) (1.0.3.4)
Requirement already satisfied: pandas>=0.19.2 in c:\users\pfeif\miniconda3\envs\landlab_dev\lib\site-packages (from xarray->landlab==1.9.0+176.gd414df44d.dirty) (0.24.2)
Requirement already satisfied: MarkupSafe>=0.23 in c:\users\pfeif\miniconda3\envs\landlab_dev\lib\site-packages (from jinja2->bmipy<1->landlab==1.9.0+176.gd414df44d.dirty) (1.1.1)
Requirement already satisfied: attrs>=18.1.0 in c:\users\pfeif\miniconda3\envs\landlab_dev\lib\site-packages (from black->bmipy<1->landlab==1.9.0+176.gd414df44d.dirty) (19.1.0)
Requirement already satisfied: appdirs in c:\users\pfeif\miniconda3\envs\landlab_dev\lib\site-packages (from black->bmipy<1->landlab==1.9.0+176.gd414df44d.dirty) (1.4.3)
Requirement already satisfied: toml>=0.9.4 in c:\users\pfeif\miniconda3\envs\landlab_dev\lib\site-packages (from black->bmipy<1->landlab==1.9.0+176.gd414df44d.dirty) (0.10.0)
Requirement already satisfied: setuptools in c:\users\pfeif\miniconda3\envs\landlab_dev\lib\site-packages (from kiwisolver>=1.0.1->matplotlib->landlab==1.9.0+176.gd414df44d.dirty) (41.0.1)
Requirement already satisfied: pytz>=2011k in c:\users\pfeif\miniconda3\envs\landlab_dev\lib\site-packages (from pandas>=0.19.2->xarray->landlab==1.9.0+176.gd414df44d.dirty) (2019.1)
Installing collected packages: landlab
  Found existing installation: landlab 1.9.0b4+165.gc9abaa74
    Uninstalling landlab-1.9.0b4+165.gc9abaa74:
      Successfully uninstalled landlab-1.9.0b4+165.gc9abaa74
  Running setup.py develop for landlab
    ERROR: Complete output from command 'C:\Users\pfeif\Miniconda3\envs\landlab_dev\python.exe' -c 'import setuptools, tokenize;__file__='"'"'C:\\Users\\pfeif\\Documents\\GitHub\\landlab\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps:
    ERROR: running develop
    running egg_info
    writing landlab.egg-info\PKG-INFO
    writing dependency_links to landlab.egg-info\dependency_links.txt
    writing entry points to landlab.egg-info\entry_points.txt
    writing requirements to landlab.egg-info\requires.txt
    writing top-level names to landlab.egg-info\top_level.txt
    reading manifest file 'landlab.egg-info\SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    warning: no files found matching 'ez_setup.py'
    warning: no files found matching 'README.md'
    writing manifest file 'landlab.egg-info\SOURCES.txt'
    running build_ext
    skipping 'landlab\ca\cfuncs.c' Cython extension (up-to-date)
    skipping 'landlab\components\drainage_density\cfuncs.c' Cython extension (up-to-date)
    skipping 'landlab\components\erosion_deposition\cfuncs.c' Cython extension (up-to-date)
    skipping 'landlab\components\flexure\cfuncs.c' Cython extension (up-to-date)
    skipping 'landlab\components\flexure\ext\flexure1d.c' Cython extension (up-to-date)
    skipping 'landlab\components\flow_accum\cfuncs.c' Cython extension (up-to-date)
    skipping 'landlab\components\flow_director\cfuncs.c' Cython extension (up-to-date)
    skipping 'landlab\components\space\cfuncs.c' Cython extension (up-to-date)
    skipping 'landlab\components\stream_power\cfuncs.c' Cython extension (up-to-date)
    skipping 'landlab\graph\cfuncs.c' Cython extension (up-to-date)
    skipping 'landlab\graph\hex\ext\hex.c' Cython extension (up-to-date)
    skipping 'landlab\graph\matrix\ext\at_patch.c' Cython extension (up-to-date)
    skipping 'landlab\graph\matrix\ext\matrix.c' Cython extension (up-to-date)
    skipping 'landlab\graph\object\ext\at_node.c' Cython extension (up-to-date)
    skipping 'landlab\graph\object\ext\at_patch.c' Cython extension (up-to-date)
    skipping 'landlab\graph\quantity\ext\of_link.c' Cython extension (up-to-date)
    skipping 'landlab\graph\quantity\ext\of_patch.c' Cython extension (up-to-date)
    skipping 'landlab\graph\sort\ext\argsort.c' Cython extension (up-to-date)
    skipping 'landlab\graph\sort\ext\remap_element.c' Cython extension (up-to-date)
    skipping 'landlab\graph\sort\ext\spoke_sort.c' Cython extension (up-to-date)
    skipping 'landlab\graph\structured_quad\ext\at_cell.c' Cython extension (up-to-date)
    skipping 'landlab\graph\structured_quad\ext\at_face.c' Cython extension (up-to-date)
    skipping 'landlab\graph\structured_quad\ext\at_link.c' Cython extension (up-to-date)
    skipping 'landlab\graph\structured_quad\ext\at_node.c' Cython extension (up-to-date)
    skipping 'landlab\graph\structured_quad\ext\at_patch.c' Cython extension (up-to-date)
    skipping 'landlab\graph\voronoi\ext\delaunay.c' Cython extension (up-to-date)
    skipping 'landlab\graph\voronoi\ext\voronoi.c' Cython extension (up-to-date)
    skipping 'landlab\grid\cfuncs.c' Cython extension (up-to-date)
    skipping 'landlab\grid\structured_quad\cfuncs.c' Cython extension (up-to-date)
    skipping 'landlab\grid\structured_quad\c_faces.c' Cython extension (up-to-date)
    skipping 'landlab\layers\ext\eventlayers.c' Cython extension (up-to-date)
    skipping 'landlab\utils\ext\jaggedarray.c' Cython extension (up-to-date)
    copying build\lib.win-amd64-3.7\landlab\ca\cfuncs.cp37-win_amd64.pyd -> landlab\ca
    copying build\lib.win-amd64-3.7\landlab\components\drainage_density\cfuncs.cp37-win_amd64.pyd -> landlab\components\drainage_density
    copying build\lib.win-amd64-3.7\landlab\components\erosion_deposition\cfuncs.cp37-win_amd64.pyd -> landlab\components\erosion_deposition
    copying build\lib.win-amd64-3.7\landlab\components\flexure\cfuncs.cp37-win_amd64.pyd -> landlab\components\flexure
    copying build\lib.win-amd64-3.7\landlab\components\flexure\ext\flexure1d.cp37-win_amd64.pyd -> landlab\components\flexure\ext
    copying build\lib.win-amd64-3.7\landlab\components\flow_accum\cfuncs.cp37-win_amd64.pyd -> landlab\components\flow_accum
    copying build\lib.win-amd64-3.7\landlab\components\flow_director\cfuncs.cp37-win_amd64.pyd -> landlab\components\flow_director
    copying build\lib.win-amd64-3.7\landlab\components\space\cfuncs.cp37-win_amd64.pyd -> landlab\components\space
    copying build\lib.win-amd64-3.7\landlab\components\stream_power\cfuncs.cp37-win_amd64.pyd -> landlab\components\stream_power
    copying build\lib.win-amd64-3.7\landlab\graph\cfuncs.cp37-win_amd64.pyd -> landlab\graph
    copying build\lib.win-amd64-3.7\landlab\graph\hex\ext\hex.cp37-win_amd64.pyd -> landlab\graph\hex\ext
    copying build\lib.win-amd64-3.7\landlab\graph\matrix\ext\at_patch.cp37-win_amd64.pyd -> landlab\graph\matrix\ext
    copying build\lib.win-amd64-3.7\landlab\graph\matrix\ext\matrix.cp37-win_amd64.pyd -> landlab\graph\matrix\ext
    copying build\lib.win-amd64-3.7\landlab\graph\object\ext\at_node.cp37-win_amd64.pyd -> landlab\graph\object\ext
    copying build\lib.win-amd64-3.7\landlab\graph\object\ext\at_patch.cp37-win_amd64.pyd -> landlab\graph\object\ext
    error: could not delete 'landlab\graph\object\ext\at_patch.cp37-win_amd64.pyd': Access is denied
    ----------------------------------------
  Rolling back uninstall of landlab
  Moving to c:\users\pfeif\miniconda3\envs\landlab_dev\lib\site-packages\landlab.egg-link
   from C:\Users\pfeif\AppData\Local\Temp\pip-uninstall-2o02vu_j\landlab.egg-link
  Moving to c:\users\pfeif\miniconda3\envs\landlab_dev\scripts\landlab-script.py
   from C:\Users\pfeif\AppData\Local\Temp\pip-uninstall-05gbqbvh\landlab-script.py
  Moving to c:\users\pfeif\miniconda3\envs\landlab_dev\scripts\landlab.exe
   from C:\Users\pfeif\AppData\Local\Temp\pip-uninstall-05gbqbvh\landlab.exe
ERROR: Command "'C:\Users\pfeif\Miniconda3\envs\landlab_dev\python.exe' -c 'import setuptools, tokenize;__file__='"'"'C:\\Users\\pfeif\\Documents\\GitHub\\landlab\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps" failed with error code 1 in C:\Users\pfeif\Documents\GitHub\landlab\
(landlab_dev) PS C:\Users\pfeif\Documents\GitHub\landlab>```

**Comment by kbarnhart** [comment]
@mcflugen any recommendations would be helpful. 

Also. After receiving questions about various errors associated with missing packages, that came from changes that we made to where dependencies are described, I updated the "Updating" section of the wiki [here](https://github.com/landlab/landlab/wiki/Updating-Landlab#fundamental-update-instructions). 

I think this is correct, but am not 100% sure. If it needs to be changed... let me know.

**Comment by mcflugen** [comment]
@kbarnhart, @pfeiffea I'm trying to reproduce this but haven't yet been able.

@pfeiffea, Does the file `landlab\graph\object\ext\at_patch.cp37-win_amd64.pyd` exist? If so, are you able to delete it?

**Comment by pfeiffea** [comment]
Yes it exists and yes I was able to delete it. Now I get a new error (pasted below). 

```(landlab_dev) PS C:\Users\pfeif\Documents\GitHub\landlab> pytest
================================================= test session starts =================================================
platform win32 -- Python 3.7.3, pytest-5.0.1, py-1.8.0, pluggy-0.12.0
rootdir: C:\Users\pfeif\Documents\GitHub\landlab, inifile: setup.cfg, testpaths: landlab
plugins: cov-2.7.1, datadir-1.3.0
collected 0 items / 1 errors

======================================================= ERRORS ========================================================
____________________________________________ ERROR collecting test session ____________________________________________
Traceback (most recent call last):
  File "C:\Users\pfeif\Miniconda3\envs\landlab_dev\lib\site-packages\_pytest\config\__init__.py", line 415, in _importconftest
    return self._conftestpath2mod[conftestpath]
KeyError: local('C:\\Users\\pfeif\\Documents\\GitHub\\landlab\\landlab\\tests\\conftest.py')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\pfeif\Miniconda3\envs\landlab_dev\lib\site-packages\_pytest\config\__init__.py", line 421, in _importconftest
    mod = conftestpath.pyimport()
  File "C:\Users\pfeif\Miniconda3\envs\landlab_dev\lib\site-packages\py\_path\local.py", line 701, in pyimport
    __import__(modname)
  File "C:\Users\pfeif\Documents\GitHub\landlab\landlab\__init__.py", line 29, in <module>
    from .grid import (
  File "C:\Users\pfeif\Documents\GitHub\landlab\landlab\grid\__init__.py", line 13, in <module>
    from .create import create_and_initialize_grid, create_grid
  File "C:\Users\pfeif\Documents\GitHub\landlab\landlab\grid\create.py", line 8, in <module>
    from ..io import read_esri_ascii
  File "C:\Users\pfeif\Documents\GitHub\landlab\landlab\io\__init__.py", line 17, in <module>
    from .shapefile import read_shapefile
  File "C:\Users\pfeif\Documents\GitHub\landlab\landlab\io\shapefile\__init__.py", line 1, in <module>
    from .read_shapefile import read_shapefile
  File "C:\Users\pfeif\Documents\GitHub\landlab\landlab\io\shapefile\read_shapefile.py", line 9, in <module>
    from landlab.grid.network import NetworkModelGrid
  File "C:\Users\pfeif\Documents\GitHub\landlab\landlab\grid\network.py", line 13, in <module>
    from ..graph import NetworkGraph
  File "C:\Users\pfeif\Documents\GitHub\landlab\landlab\graph\__init__.py", line 1, in <module>
    from .dual import DualGraph
  File "C:\Users\pfeif\Documents\GitHub\landlab\landlab\graph\dual.py", line 11, in <module>
    from .graph import Graph, find_perimeter_nodes
  File "C:\Users\pfeif\Documents\GitHub\landlab\landlab\graph\graph.py", line 69, in <module>
    from .object.at_patch import get_nodes_at_patch
  File "C:\Users\pfeif\Documents\GitHub\landlab\landlab\graph\object\at_patch.py", line 3, in <module>
    from .ext.at_patch import get_nodes_at_patch as _get_nodes_at_patch
ModuleNotFoundError: No module named 'landlab.graph.object.ext.at_patch'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\pfeif\Miniconda3\envs\landlab_dev\lib\site-packages\py\_path\common.py", line 377, in visit
    for x in Visitor(fil, rec, ignore, bf, sort).gen(self):
  File "C:\Users\pfeif\Miniconda3\envs\landlab_dev\lib\site-packages\py\_path\common.py", line 418, in gen
    dirs = self.optsort([p for p in entries
  File "C:\Users\pfeif\Miniconda3\envs\landlab_dev\lib\site-packages\py\_path\common.py", line 419, in <listcomp>
    if p.check(dir=1) and (rec is None or rec(p))])
  File "C:\Users\pfeif\Miniconda3\envs\landlab_dev\lib\site-packages\_pytest\main.py", line 622, in _recurse
    ihook = self.gethookproxy(dirpath)
  File "C:\Users\pfeif\Miniconda3\envs\landlab_dev\lib\site-packages\_pytest\main.py", line 446, in gethookproxy
    my_conftestmodules = pm._getconftestmodules(fspath)
  File "C:\Users\pfeif\Miniconda3\envs\landlab_dev\lib\site-packages\_pytest\config\__init__.py", line 399, in _getconftestmodules
    mod = self._importconftest(conftestpath.realpath())
  File "C:\Users\pfeif\Miniconda3\envs\landlab_dev\lib\site-packages\_pytest\config\__init__.py", line 438, in _importconftest
    raise ConftestImportFailure(conftestpath, sys.exc_info())
_pytest.config.ConftestImportFailure: (local('C:\\Users\\pfeif\\Documents\\GitHub\\landlab\\landlab\\tests\\conftest.py'), (<class 'ModuleNotFoundError'>, ModuleNotFoundError("No module named 'landlab.graph.object.ext.at_patch'"), <traceback object at 0x000002034CE21588>))```
