### ISSUE TITLE
Install errors due to netcdf4

### ISSUE THREAD

**Issue by kbarnhart** [landlab/landlab#993]
In the last day or so, windows builds have started to fail due to a failure to install netCDF4 ([for example, this one](https://ci.appveyor.com/project/mcflugen/landlab/builds/27206166)).

```
Executing: pip install -e .
265Obtaining file:///C:/projects/landlab
266Collecting bmipy<1 (from landlab==1.9.0+91.gfcc04288)
267  Downloading https://files.pythonhosted.org/packages/f5/c8/b7f33ad23a89ce0632c45bfdd1fc64928f300ef5bbf826eb29389887a2d4/bmipy-0.3.2.tar.gz
268Collecting matplotlib (from landlab==1.9.0+91.gfcc04288)
269  Downloading https://files.pythonhosted.org/packages/21/93/759d9f5a6c4b5c1fb489bb57200fc2f553c524642bc2756ae2528dbed6b5/matplotlib-2.2.4-cp27-cp27m-win_amd64.whl (8.7MB)
270Collecting netcdf4 (from landlab==1.9.0+91.gfcc04288)
271  Downloading https://files.pythonhosted.org/packages/64/2e/abc0bce095ab5a3b8374f052ace2509a031fd7633b23917e557487067225/netCDF4-1.5.2.tar.gz (801kB)
272    Complete output from command python setup.py egg_info:
273    reading from setup.cfg...
274    
275        HDF5_DIR environment variable not set, checking some standard locations ..
276    checking C:\Users\appveyor ...
277    checking /usr/local ...
278    checking /sw ...
279    checking /opt ...
280    checking /opt/local ...
281    checking /usr ...
282    Traceback (most recent call last):
283      File "<string>", line 1, in <module>
284      File "c:\users\appveyor\appdata\local\temp\1\pip-install-imu4ke\netcdf4\setup.py", line 397, in <module>
285        _populate_hdf5_info(dirstosearch, inc_dirs, libs, lib_dirs)
286      File "c:\users\appveyor\appdata\local\temp\1\pip-install-imu4ke\netcdf4\setup.py", line 345, in _populate_hdf5_info
287        raise ValueError('did not find HDF5 headers')
288    ValueError: did not find HDF5 headers
289    
290    ----------------------------------------
291Command "python setup.py egg_info" failed with error code 1 in c:\users\appveyor\appdata\local\temp\1\pip-install-imu4ke\netcdf4\
```

I think this is because on 9/3/2019 netcdf4 made a new release on PyPI of v1.5.2 (up from 1.5.1.2), and this doesn't have a windows build on PyPI. [PyPI Files for 1.5.2 Here](https://pypi.org/project/netCDF4/1.5.2/#files).

This contrasts to the [PyPI files for 1.5.1.2](https://pypi.org/project/netCDF4/1.5.1.2/#files) which has a wheel for windows. 

@mcflugen do you think this is the source of the problem?

What's the right solution, post an issue on the netcdf GitHub page to request that they make the windows build?

**Comment by kbarnhart** [comment]
looks like windows wheels have been uploaded. Closing.
